In [30]:
import csv
import os

In [31]:
str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/"

In [32]:
for file in os.listdir(str):
    d = os.path.join(str, file)
    if os.path.isdir(d):
        print(d)

/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Breast cancer prediction
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/DataBases
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/UW ML
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Source Article
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Source Figures
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML 2018 ESU
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Real World ML Bcode
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/COVID 19 Excercise
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Basics
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/OtherDoc
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/awesome papers
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Excercise
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/data download 201957
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML

In [33]:
import os
files = []
def listdirs(str):
    for file in os.listdir(str):
        d = os.path.join(str, file)
        if os.path.isdir(d):
            print(d)
            listdirs(d)    
str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/"
listdirs(str)

/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise5
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise5/Figures
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise5/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise5/Data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise2
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise2/Figures
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise2/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise2/Data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise3
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise3/Figures
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise3/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise3/Data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise4
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise4/Figures
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise4/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise4/Data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise8
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise8/Figures
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise8/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise8/Data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise1
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise1/Figures
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise1/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise1/Data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise6
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise6/Figures
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise6/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise6/Data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise7
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise7/Figures
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise7/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments/Exercise7/Data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Breast cancer prediction
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Breast cancer prediction/pictures
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Breast cancer prediction/.github
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Breast cancer prediction/.github/workflows
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Breast cancer prediction/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/DataBases
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/DataBases/AssigmentsData
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/DataBases/covid19-global-forecasting-week-1
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch07
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch07/EXTRAS
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch09
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch08
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch08/setHtml
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch06
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch06/EXTRAS
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch12
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch15
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch14
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch13
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch13/extras
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch04
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch04/email
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch04/email/spam
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch04/email/ham
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch04/EXTRAS
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch03
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch02
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch02/EXTRAS
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch05
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/Ch05/EXTRAS
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/0d
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/95
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/59
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/92
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/3e
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/50
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/68
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/57
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/3b
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/6f
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/03
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/9b
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/9e
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/04
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/6a
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/35
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/69
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/3c
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/51
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/3d
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/58
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/0b
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/94
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/0e
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/5f
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/05
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/9d
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/9c
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/a3
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/ac
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/ad
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/bb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/d7
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/d0
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/b3
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/df
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/a2
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/a5
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/bc
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/ab
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/e2
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/f4
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/f3
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/c7
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/ee
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/fd
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/f2
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/f5
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/e3
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/ca
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/fe
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/c8
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/fb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/ed
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/ec
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/4e
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/20
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/18
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/27
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/4b
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/pack
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/11
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/7d
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/29
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/16
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/89
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/1f
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/73
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/80
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/1a
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/17
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/7b
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/8f
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/8a
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/10
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/4d
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/75
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/81
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/86
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/44
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/2a
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/43
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/07
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/38
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/00
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/6e
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/9a
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/5c
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/09
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/5d
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/31
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/info
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/91
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/65
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/62
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/3a
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/54
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/98
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/53
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/3f
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/5e
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/08
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/6d
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/01
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/39
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/99
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/52
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/55
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/97
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/0f
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/0a
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/64
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/bf
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/d4
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/ba
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/a0
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/a7
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/b8
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/dd
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/dc
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/b6
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode/.git/objects/a9

/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week4- Clustering
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/final-project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week1- Machine Learning
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week5- Recommender Systems
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week2- From Understanding to Preparation and From Modelin to Evaluation
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week1- From Problem to Approach and From Requirements to Collection
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week3- From Deployment to Feedback
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/capstone-project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module2
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module1
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week5- Fake Album Cover Game
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week1- Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week3 - Exploratory Data Analysis
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week5 - Model Evaluation
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week2 - Data Wrangling
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week4 - Model Development
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/week1- Network Labs and Jupyter
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/week2- Apache Zeppelin Notebooks and RStudio IDE
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week4- Assignment
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week2- Advanced SQL
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week2- Advanced SQL/lab
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week1- Databases and SQL
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week3 - Advanced Visualizations and Geospatial Data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week1 - Data Visualization Tools
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week2 - Basic and Specialized Visualization Tools
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Real World ML Bcode
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Real World ML Bcode/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/COVID 19 Excercise
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Basics
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Basics/mathematical-basics
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Basics/classification-problems
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Basics/classification-problems/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Basics/legacy
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Basics/legacy/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Basics/information gain
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Basics/regression-problems
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Basics/regression-problems/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/OtherDoc
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/awesome papers
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/awesome papers/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-13-Logistic_regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-13-Logistic_regression/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-13-Logistic_regression/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-13-Logistic_regression/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-13-Logistic_regression/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-13-Logistic_regression/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-11-Feature_Engineering_crucible
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-11-Feature_Engineering_crucible/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-12-Feature_Selection
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-12-Feature_Selection/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-12-Feature_Selection/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-12-Feature_Selection/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-12-Feature_Selection/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-12-Feature_Selection/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/RobinSidel
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/LynnleyBrowning
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/KouroshKarimkhany
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/MichaelConnor
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/JoeOrtiz
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/EricAuchard
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/AaronPressman
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/SimonCowell
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/LynneO'Donnell
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/EdnaFernandes
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/KevinMorrison
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/SamuelPerry
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/PatriciaCommins
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/JohnMastrini

/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/JanLopatka
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/KevinDrawbaugh
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/KarlPenhaul
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/MartinWolk
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/ScottHillis
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/DavidLawder
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/FumikoFujisaki
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/MarcelMichelson
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/NickLouth
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/DarrenSchuettler
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/WilliamKazer
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/TanEeLyn
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/PierreTran
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/HeatherScoffield
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/MureDickie
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/RogerFillion
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/JimGilchrist
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/BradDorfman
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/AlanCrosby
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/JonathanBirt
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/BenjaminKangLim
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/TheresePoletti
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/KeithWeir
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/JoWinterbottom
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/MarkBendeich
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/JaneMacartney
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/MatthewBunce
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/ToddNissen
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/PeterHumphrey
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/TimFarrand
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/SarahDavison
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/GrahamEarnshaw
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/BernardHickey
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/KirstinRidley
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/AlexanderSmith
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50test/LydiaZajc
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/RobinSidel
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/LynnleyBrowning
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/KouroshKarimkhany
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/MichaelConnor
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/JoeOrtiz
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/EricAuchard
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/AaronPressman
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/SimonCowell
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/LynneO'Donnell
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/EdnaFernandes
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/KevinMorrison
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/SamuelPerry
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/PatriciaCommins
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/JohnMastrini
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/JanLopatka
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/KevinDrawbaugh
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/KarlPenhaul
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/MartinWolk
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/ScottHillis
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/DavidLawder
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/FumikoFujisaki
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/MarcelMichelson
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/NickLouth
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/DarrenSchuettler
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/WilliamKazer
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/TanEeLyn
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/PierreTran
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/HeatherScoffield
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/MureDickie
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/RogerFillion
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/JimGilchrist
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/BradDorfman
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/AlanCrosby
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/JonathanBirt
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/BenjaminKangLim
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/TheresePoletti
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/KeithWeir
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/JoWinterbottom
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/MarkBendeich
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/JaneMacartney
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/MatthewBunce
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/ToddNissen
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/PeterHumphrey
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/TimFarrand
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/SarahDavison
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/GrahamEarnshaw
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/BernardHickey
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/KirstinRidley
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/AlexanderSmith
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/data/C50train/LydiaZajc
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-21-nlp_introduction/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-02-Numpy-Basic
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-02-Numpy-Basic/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-02-Numpy-Basic/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-02-Numpy-Basic/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-02-Numpy-Basic/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-02-Numpy-Basic/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-10-Advanced_linear_regression_crucible
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-10-Advanced_linear_regression_crucible/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-12-Feature_Selection_crucible
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-12-Feature_Selection_crucible/sales-prediction
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-12-Feature_Selection_crucible/sales-prediction/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-12-Feature_Selection_crucible/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-04-Pandas-Advanced
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-04-Pandas-Advanced/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-04-Pandas-Advanced/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-04-Pandas-Advanced/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-04-Pandas-Advanced/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-04-Pandas-Advanced/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-06-Descriptive_Stats
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-06-Descriptive_Stats/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-06-Descriptive_Stats/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-06-Descriptive_Stats/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-06-Descriptive_Stats/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-14-Decision_Tree
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-14-Decision_Tree/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-14-Decision_Tree/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-14-Decision_Tree/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-14-Decision_Tree/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-14-Decision_Tree/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/RobinSidel

/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/LynnleyBrowning
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/KouroshKarimkhany
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/MichaelConnor
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/JoeOrtiz
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/EricAuchard
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/AaronPressman
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/SimonCowell
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/LynneO'Donnell
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/EdnaFernandes
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/KevinMorrison
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/SamuelPerry
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/PatriciaCommins
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/JohnMastrini
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/JanLopatka
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/KevinDrawbaugh
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/KarlPenhaul
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/MartinWolk
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/ScottHillis
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/DavidLawder
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/FumikoFujisaki
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/MarcelMichelson
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/NickLouth
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/DarrenSchuettler
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/WilliamKazer
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/TanEeLyn
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/PierreTran
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/HeatherScoffield
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/MureDickie
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/RogerFillion
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/JimGilchrist
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/BradDorfman
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/AlanCrosby
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/JonathanBirt
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/BenjaminKangLim
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/TheresePoletti
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/KeithWeir
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/JoWinterbottom
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/MarkBendeich
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/JaneMacartney
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/MatthewBunce
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/ToddNissen
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/PeterHumphrey
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/TimFarrand
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/SarahDavison
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/GrahamEarnshaw
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/BernardHickey
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/KirstinRidley
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/AlexanderSmith
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50test/LydiaZajc
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/RobinSidel
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/LynnleyBrowning
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/KouroshKarimkhany
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/MichaelConnor
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/JoeOrtiz
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/EricAuchard
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/AaronPressman
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/SimonCowell
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/LynneO'Donnell
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/EdnaFernandes
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/KevinMorrison
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/SamuelPerry
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/PatriciaCommins
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/JohnMastrini
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/JanLopatka
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/KevinDrawbaugh
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/KarlPenhaul
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/MartinWolk
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/ScottHillis
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/DavidLawder
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/FumikoFujisaki
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/MarcelMichelson
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/NickLouth
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/DarrenSchuettler
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/WilliamKazer
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/TanEeLyn
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/PierreTran
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/HeatherScoffield
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/MureDickie
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/RogerFillion
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/JimGilchrist
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/BradDorfman
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/AlanCrosby
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/JonathanBirt
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/BenjaminKangLim
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/TheresePoletti
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/KeithWeir

/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/JoWinterbottom
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/MarkBendeich
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/JaneMacartney
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/MatthewBunce
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/ToddNissen
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/PeterHumphrey
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/TimFarrand
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/SarahDavison
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/GrahamEarnshaw
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/BernardHickey
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/KirstinRidley
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/AlexanderSmith
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/data/C50train/LydiaZajc
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-22-nlp_intermediate/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-18-Clustering
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-18-Clustering/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-18-Clustering/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-18-Clustering/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-18-Clustering/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-18-Clustering/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-13-Logistic_regression_crucible
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-13-Logistic_regression_crucible/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-16-Gradient_Boosting_crucibles
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-16-Gradient_Boosting_crucibles/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-07-Inferential_Stats
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-07-Inferential_Stats/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-07-Inferential_Stats/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-07-Inferential_Stats/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-07-Inferential_Stats/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-07-Inferential_Stats/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-05-visualization-matplotlib
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-05-visualization-matplotlib/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-05-visualization-matplotlib/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-05-visualization-matplotlib/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-05-visualization-matplotlib/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-05-visualization-matplotlib/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-17-Challenges_in_ml
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-17-Challenges_in_ml/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-17-Challenges_in_ml/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-17-Challenges_in_ml/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-17-Challenges_in_ml/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-17-Challenges_in_ml/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-08-Linear_Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-08-Linear_Regression/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-08-Linear_Regression/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-08-Linear_Regression/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-08-Linear_Regression/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-08-Linear_Regression/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-15-Ensembling_&_Random_Forest
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-15-Ensembling_&_Random_Forest/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-15-Ensembling_&_Random_Forest/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-15-Ensembling_&_Random_Forest/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-15-Ensembling_&_Random_Forest/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-15-Ensembling_&_Random_Forest/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-26-NLP-Project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-26-NLP-Project/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-26-NLP-Project/images/icons
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-26-NLP-Project/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-26-NLP-Project/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-26-NLP-Project/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-10-Advanced_linear_regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-10-Advanced_linear_regression/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-10-Advanced_linear_regression/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-10-Advanced_linear_regression/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-10-Advanced_linear_regression/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-10-Advanced_linear_regression/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/RobinSidel
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/LynnleyBrowning
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/KouroshKarimkhany
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/MichaelConnor
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/JoeOrtiz
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/EricAuchard
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/AaronPressman
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/SimonCowell
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/LynneO'Donnell
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/EdnaFernandes
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/KevinMorrison
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/SamuelPerry
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/PatriciaCommins
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/JohnMastrini
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/JanLopatka
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/KevinDrawbaugh
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/KarlPenhaul
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/MartinWolk
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/ScottHillis
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/DavidLawder
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/FumikoFujisaki
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/MarcelMichelson
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/NickLouth
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/DarrenSchuettler
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/WilliamKazer
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/TanEeLyn

/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/PierreTran
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/HeatherScoffield
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/MureDickie
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/RogerFillion
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/JimGilchrist
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/BradDorfman
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/AlanCrosby
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/JonathanBirt
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/BenjaminKangLim
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/TheresePoletti
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/KeithWeir
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/JoWinterbottom
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/MarkBendeich
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/JaneMacartney
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/MatthewBunce
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/ToddNissen
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/PeterHumphrey
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/TimFarrand
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/SarahDavison
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/GrahamEarnshaw
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/BernardHickey
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/KirstinRidley
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/AlexanderSmith
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50test/LydiaZajc
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/RobinSidel
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/LynnleyBrowning
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/KouroshKarimkhany
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/MichaelConnor
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/JoeOrtiz
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/EricAuchard
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/AaronPressman
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/SimonCowell
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/LynneO'Donnell
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/EdnaFernandes
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/KevinMorrison
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/SamuelPerry
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/PatriciaCommins
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/JohnMastrini
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/JanLopatka
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/KevinDrawbaugh
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/KarlPenhaul
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/MartinWolk
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/ScottHillis
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/DavidLawder
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/FumikoFujisaki
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/MarcelMichelson
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/NickLouth
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/DarrenSchuettler
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/WilliamKazer
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/TanEeLyn
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/PierreTran
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/HeatherScoffield
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/MureDickie
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/RogerFillion

/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/JimGilchrist
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/BradDorfman
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/AlanCrosby
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/JonathanBirt
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/BenjaminKangLim
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/TheresePoletti
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/KeithWeir
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/JoWinterbottom
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/MarkBendeich
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/JaneMacartney
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/MatthewBunce
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/ToddNissen
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/PeterHumphrey
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/TimFarrand
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/SarahDavison
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/GrahamEarnshaw
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/BernardHickey
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/KirstinRidley
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/AlexanderSmith
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/C50train/LydiaZajc
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/data/ml-100k
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-23-Introduction to Recommender Systems/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-11-Feature_Engineering
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-11-Feature_Engineering/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-11-Feature_Engineering/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-11-Feature_Engineering/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-11-Feature_Engineering/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-11-Feature_Engineering/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-24-Support_Vector_Machines
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-24-Support_Vector_Machines/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-24-Support_Vector_Machines/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-24-Support_Vector_Machines/notebook
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-24-Support_Vector_Machines/notebook/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-24-Support_Vector_Machines/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-25-Productionizing ML - Deployment on AWS
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-25-Productionizing ML - Deployment on AWS/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-25-Productionizing ML - Deployment on AWS/images/icons
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-25-Productionizing ML - Deployment on AWS/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-25-Productionizing ML - Deployment on AWS/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-25-Productionizing ML - Deployment on AWS/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-09-Exploratory_Data_Analysis
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-09-Exploratory_Data_Analysis/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-09-Exploratory_Data_Analysis/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-09-Exploratory_Data_Analysis/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-09-Exploratory_Data_Analysis/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-09-Exploratory_Data_Analysis/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-09-Exploratory_Data_Analysis/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-15-Ensembling_&_Random_Forest_crucible
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-15-Ensembling_&_Random_Forest_crucible/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-18-Clustering_crucible
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-18-Clustering_crucible/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-03-Numpy_advanced_Pandas_basic
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-03-Numpy_advanced_Pandas_basic/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-03-Numpy_advanced_Pandas_basic/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-03-Numpy_advanced_Pandas_basic/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-03-Numpy_advanced_Pandas_basic/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-03-Numpy_advanced_Pandas_basic/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-03-Numpy_advanced_Pandas_basic/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-01-Git_&_Python_intro
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-01-Git_&_Python_intro/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-01-Git_&_Python_intro/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-01-Git_&_Python_intro/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-01-Git_&_Python_intro/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-01-Git_&_Python_intro/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-20-Timeseries_2
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-20-Timeseries_2/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-20-Timeseries_2/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-20-Timeseries_2/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-20-Timeseries_2/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-20-Timeseries_2/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-16-Gradient_Boosting
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-16-Gradient_Boosting/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-16-Gradient_Boosting/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-16-Gradient_Boosting/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-16-Gradient_Boosting/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-16-Gradient_Boosting/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-19-Timeseries_1
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-19-Timeseries_1/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-19-Timeseries_1/images/icon
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-19-Timeseries_1/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-19-Timeseries_1/notebooks
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-19-Timeseries_1/notebooks/__pycache__
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master/Week-19-Timeseries_1/notebooks/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Excercise
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Excercise/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/Classification
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/Classification/Principal-Component-Analysis
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/Classification/Principal-Component-Analysis/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/Classification/K-Nearest-Neighbors
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/Classification/K-Nearest-Neighbors/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/Classification/Support-Vector-Machines
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/Classification/Support-Vector-Machines/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/Classification/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/Classification/Decision-Trees-and-Random-Forests
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/Classification/Decision-Trees-and-Random-Forests/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/ML Projects sklearn
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/ML Projects sklearn/docs
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/ML Projects sklearn/img
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/ML Projects sklearn/scikit
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/ML Projects sklearn/scikit/Chapter_1
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/ML Projects sklearn/scikit/Chapter_1/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/ML Projects sklearn/scikit/Chapter_2
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/ML Projects sklearn/scikit/Chapter_2/figures
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/ML Projects sklearn/scikit/Chapter_2/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/ML Projects sklearn/scikit/Chapter_3
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/ML Projects sklearn/data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/ML Projects sklearn/data/MNIST
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/ML Projects sklearn/src
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/ML Projects sklearn/src/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/docker
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/docker/bin
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/images
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/images/training_linear_models
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/images/classification
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/images/fundamentals
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/images/ensembles
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/images/ann
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/images/distributed
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/images/decision_trees
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/images/deep
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/images/svm
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/images/cnn
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/images/unsupervised_learning
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/images/tensorflow
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/images/nlp
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/images/autoencoders
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/images/rl
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/images/rnn
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/images/end_to_end_project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/work_in_progress
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/datasets
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/datasets/inception
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/datasets/lifesat
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python/handson-ml book/datasets/housing

/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 5/cats_and_dogs_filtered/train/cats
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 5/cats_and_dogs_filtered/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 5/cats_and_dogs_filtered/validation
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 5/cats_and_dogs_filtered/validation/dogs
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 5/cats_and_dogs_filtered/validation/cats
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 5/Transfer Learning approach
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 5/Transfer Learning approach/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 5/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 4
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 4/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 4/outputs
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 3
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 3/Toxic comments
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 3/Toxic comments/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 3/TF projector Toxic comments
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 3/Loan Status
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 3/Loan Status/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 3/Cereals
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 3/Cereals/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 3/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 3/outputs
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 8
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 8/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 8/outputs
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 6
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 6/Fashion MNIST
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 6/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 6/outputs
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 6/outputs/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 1
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 1/task
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 1/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 1/outputs
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 7
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 7/Twitter
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 7/TF Projector IMDB
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 7/IMDB
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 7/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML /Day 7/outputs

In [34]:
import os 
str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/"
for it in os.scandir(str):
    if it.is_dir():
        print(it.path)

/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Coursera Python Assignments
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Breast cancer prediction
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/DataBases
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML action Bcode
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/UW ML
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Source Article
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Source Figures
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML 2018 ESU
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Real World ML Bcode
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/COVID 19 Excercise
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Basics
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/OtherDoc
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/awesome papers
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/26-Weeks-Of-Data-Science-master
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Excercise
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/Machine Learning with Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/data download 201957
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/10 Days of ML

In [35]:
import os

def listdirs(str):
    for it in os.scandir(str):
        if it.is_dir():
            print(it.path)
            listdirs(it)
            
str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"
listdirs(str)

/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/01. Data Preprocessing
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/01. Simple_Linear_Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/02. Multiple_Linear_Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/04. Support Vector Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/06. Random Forest Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/05. Decision Tree Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/03. Polynomial Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/02. K-Nearest_Neighbors
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/01. Logistic_Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week4- Clustering
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/final-project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week1- Machine Learning
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week5- Recommender Systems
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week2- From Understanding to Preparation and From Modelin to Evaluation
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week1- From Problem to Approach and From Requirements to Collection
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week3- From Deployment to Feedback
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/capstone-project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module2
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module1
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week5- Fake Album Cover Game
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week1- Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week3 - Exploratory Data Analysis
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week5 - Model Evaluation
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week2 - Data Wrangling
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week4 - Model Development
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/week1- Network Labs and Jupyter
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/week2- Apache Zeppelin Notebooks and RStudio IDE
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week4- Assignment
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week2- Advanced SQL
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week2- Advanced SQL/lab
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week1- Databases and SQL
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week3 - Advanced Visualizations and Geospatial Data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week1 - Data Visualization Tools
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week2 - Basic and Specialized Visualization Tools

In [36]:
from pathlib import Path

str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"
for path in Path(str).iterdir():
    if path.is_dir():
        print(path)

/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM

In [37]:
from pathlib import Path

str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"
def listdirs(str):
    for path in Path(str).iterdir():
        if path.is_dir():
            print(path)
            listdirs(path)
listdirs(str)

/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/01. Data Preprocessing
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/01. Simple_Linear_Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/02. Multiple_Linear_Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/04. Support Vector Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/06. Random Forest Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/05. Decision Tree Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/03. Polynomial Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/02. K-Nearest_Neighbors
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/01. Logistic_Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week4- Clustering
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/final-project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week1- Machine Learning
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week5- Recommender Systems
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week2- From Understanding to Preparation and From Modelin to Evaluation
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week1- From Problem to Approach and From Requirements to Collection
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week3- From Deployment to Feedback
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/capstone-project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module2
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module1
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week5- Fake Album Cover Game
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week1- Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week3 - Exploratory Data Analysis
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week5 - Model Evaluation
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week2 - Data Wrangling
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week4 - Model Development
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/week1- Network Labs and Jupyter
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/week2- Apache Zeppelin Notebooks and RStudio IDE
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week4- Assignment
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week2- Advanced SQL
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week2- Advanced SQL/lab
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week1- Databases and SQL
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week3 - Advanced Visualizations and Geospatial Data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week1 - Data Visualization Tools
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week2 - Basic and Specialized Visualization Tools

In [38]:
import os

str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"
for rootdir, dirs, file in os.walk(str):
    for subdir in dirs:
        print(os.path.join(str, subdir))

/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/01. Data Preprocessing
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/02. Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/03. Classification
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/01. Simple_Linear_Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/02. Multiple_Linear_Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/04. Support Vector Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/06. Random Forest Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/05. Decision Tree Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/03. Polynomial Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/02. K-Nearest_Neighbors
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/01. Logistic_Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/IBM - Machine Learning with Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/IBM - Data Science Methodology
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/IBM - Applied Data Science Capstone Project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/IBM - Python for Data Science
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/IBM - Data Analysis with Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/IBM - Open Source tools for Data Science
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/IBM - Databases and SQL for Data Science
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/IBM - Data Visualization with Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week4- Clustering
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/final-project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week1- Machine Learning
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week5- Recommender Systems
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week3- Classification
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week2- Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week2- From Understanding to Preparation and From Modelin to Evaluation
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week1- From Problem to Approach and From Requirements to Collection
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week3- From Deployment to Feedback
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/capstone-project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/module3
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/module2
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/module1
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week4- Working with Data in Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week5- Fake Album Cover Game
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week2- Python Data Structures
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week1- Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week3- Python Programming
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week3 - Exploratory Data Analysis
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week5 - Model Evaluation
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week1 - Datasets
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week2 - Data Wrangling
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week4 - Model Development
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week1- Network Labs and Jupyter
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week2- Apache Zeppelin Notebooks and RStudio IDE
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week4- Assignment
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week2- Advanced SQL
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week3- Accessing Databases using Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week1- Databases and SQL
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/lab
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week3 - Advanced Visualizations and Geospatial Data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week1 - Data Visualization Tools
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/week2 - Basic and Specialized Visualization Tools

In [39]:
import glob

str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"
for path in glob.glob(f'{str}/*/'):
    print(path)

/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/

In [40]:
import glob

str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"
for path in glob.glob(f'{str}/*/**/', recursive=True):
    print(path)

/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/01. Data Preprocessing/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/01. Simple_Linear_Regression/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/02. Multiple_Linear_Regression/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/04. Support Vector Regression/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/06. Random Forest Regression/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/05. Decision Tree Regression/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/03. Polynomial Regression/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/02. K-Nearest_Neighbors/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/01. Logistic_Regression/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week4- Clustering/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/final-project/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week1- Machine Learning/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week5- Recommender Systems/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week2- From Understanding to Preparation and From Modelin to Evaluation/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week1- From Problem to Approach and From Requirements to Collection/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week3- From Deployment to Feedback/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/capstone-project/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/project/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module2/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module1/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week5- Fake Album Cover Game/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week1- Python/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week3 - Exploratory Data Analysis/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week5 - Model Evaluation/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week2 - Data Wrangling/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week4 - Model Development/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/week1- Network Labs and Jupyter/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/project/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/week2- Apache Zeppelin Notebooks and RStudio IDE/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week4- Assignment/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week2- Advanced SQL/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week2- Advanced SQL/lab/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week1- Databases and SQL/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week3 - Advanced Visualizations and Geospatial Data/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week1 - Data Visualization Tools/
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week2 - Basic and Specialized Visualization Tools/

In [41]:
import os 

str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"
for path, dirs, files in os.walk(str):
    for file in files:
        corrent = os.path.join(path, file)
        row = os.path.relpath(corrent, str).split(os.sep)
        print(row)

['.DS_Store']
['Machine-Learning-AtoZ', '.DS_Store']
['Machine-Learning-AtoZ', 'README.md']
['Machine-Learning-AtoZ', '01. Data Preprocessing', 'Data Preprocessing_G.ipynb']
['Machine-Learning-AtoZ', '01. Data Preprocessing', 'Data.csv']
['Machine-Learning-AtoZ', '02. Regression', '.DS_Store']
['Machine-Learning-AtoZ', '02. Regression', '01. Simple_Linear_Regression', 'Salary_Data.csv']
['Machine-Learning-AtoZ', '02. Regression', '01. Simple_Linear_Regression', 'Simple LinearRegression_G.ipynb']
['Machine-Learning-AtoZ', '02. Regression', '02. Multiple_Linear_Regression', '50_Startups.csv']
['Machine-Learning-AtoZ', '02. Regression', '02. Multiple_Linear_Regression', 'Multiple_Linear_Regression_G.ipynb']
['Machine-Learning-AtoZ', '02. Regression', '04. Support Vector Regression', 'Support_Vector_Regression-(SVR)_G.ipynb']
['Machine-Learning-AtoZ', '02. Regression', '06. Random Forest Regression', 'Random Forest Regression']
['Machine-Learning-AtoZ', '02. Regression', '05. Decision Tree Regression', 'Decision-Tree_Regression_G.ipynb']
['Machine-Learning-AtoZ', '02. Regression', '03. Polynomial Regression', 'Polynomial_Linear_Regression_G.ipynb']
['Machine-Learning-AtoZ', '03. Classification', '.DS_Store']
['Machine-Learning-AtoZ', '03. Classification', '02. K-Nearest_Neighbors', 'K-Nearest-Neighbor_(KNN)_Classifier_G.ipynb']
['Machine-Learning-AtoZ', '03. Classification', '01. Logistic_Regression', 'Classification-Logistic_Regression_G.ipynb']
['Applied-Data-Science-Specialization-IBM', '.DS_Store']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', '.DS_Store']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'README.md']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week4- Clustering', 'Clus-DBSCN-weather-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week4- Clustering', 'Clus-Hierarchical-Cars-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week4- Clustering', 'Clus-K-Means-Customer-Seg-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'final-project', 'final-solution.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'final-project', 'final project.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week1- Machine Learning', 'cheat-sheet.png']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week1- Machine Learning', 'supervised-vs-unsupervised.png']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week5- Recommender Systems', 'RecSys-Content-Based-movies-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week5- Recommender Systems', 'memory-based-vs-model-based.png']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week5- Recommender Systems', 'RecSys-Collaborative-Filtering-movies-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week5- Recommender Systems', 'challenges-of-collaboration.png']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week3- Classification', 'Clas-K-Nearest-neighbors-CustCat-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week3- Classification', 'entropy-and-information-gain.png']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week3- Classification', 'knn.jpg']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week3- Classification', 'Clas-Decision-Trees-drug-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week3- Classification', 'linear_vs_logistic_regression.jpg']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week3- Classification', '.ipynb_checkpoints', 'Clas-K-Nearest-neighbors-CustCat-py-v1-checkpoint.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week2- Regression', 'linear-vs-nonlinear.jpg']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week2- Regression', 'Reg-Polynomial-Regression-Co2-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week2- Regression', 'accuracy-vs-generalization.jpg']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week2- Regression', 'Reg-NoneLinearRegression-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week2- Regression', 'Reg-Mulitple-Linear-Regression-Co2-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week2- Regression', 'Reg-Simple-Linear-Regression-Co2-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Science Methodology', 'analytics-chart.png']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Science Methodology', '.DS_Store']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Science Methodology', 'data-method.jpg']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Science Methodology', 'data-science-process.png']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Science Methodology', 'README.md']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Science Methodology', 'data-science-salon-clustering-a-top-down-and-bottom-up-approach.jpg']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Science Methodology', 'sum.png']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Science Methodology', 'week2- From Understanding to Preparation and From Modelin to Evaluation', 'From-Modeling-to-Evaluation-v2.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Science Methodology', 'week2- From Understanding to Preparation and From Modelin to Evaluation', 'From-Understanding-to-Preparation-v2.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Science Methodology', 'week1- From Problem to Approach and From Requirements to Collection', 'From-Problem-to-Approach-v2.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Science Methodology', 'week1- From Problem to Approach and From Requirements to Collection', 'From-Requirements-to-Collection-v2.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Science Methodology', 'week3- From Deployment to Feedback', 'Data-Science-Tools-for-Email-Analysis-Research-Guide.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Science Methodology', 'week3- From Deployment to Feedback', 'Final-Assignment.docx']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', '.DS_Store']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'README.md']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'capstone-project', 'data.zip']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'capstone-project', 'project-notebook.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'capstone-project', 'README.md']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'capstone-project', 'capstone-project.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'module3', 'Clustering-k-means-py-v1.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'module3', '.DS_Store']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'module3', 'Neighborhoods-New-York-py-v1.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'module3', 'project', 'Segmenting and Clustering Neighborhoods in Toronto.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'module3', 'project', 'Segmenting and Clustering Neighborhoods with Coordinates.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'module3', 'project', 'Segmenting and Clustering Neighborhoods Final.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'module2', 'Foursquare-API-py-v1.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'module1', 'assignment1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', '.DS_Store']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'README.md']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week4- Working with Data in Python', 'PY0101EN-5-1-Numpy1D.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week4- Working with Data in Python', 'PY0101EN-4-2-WriteFile.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week4- Working with Data in Python', 'PY0101EN-5-2-Numpy2D.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week4- Working with Data in Python', 'PY0101EN-4-1-ReadFile.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week5- Fake Album Cover Game', 'project.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week2- Python Data Structures', 'PY0101EN-2-2-Lists.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week2- Python Data Structures', 'PY0101EN-2-1-Tuples.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week2- Python Data Structures', 'PY0101EN-2-4-Sets.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week2- Python Data Structures', 'PY0101EN-2-3-Dictionaries.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week1- Python', 'PY0101EN-1-2-Strings.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week1- Python', 'PY0101EN-1-1-Types.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week3- Python Programming', 'PY0101EN-3-3-Functions.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week3- Python Programming', 'PY0101EN-3-4-Classes.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week3- Python Programming', 'PY0101EN-3-1-Conditions.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week3- Python Programming', 'PY0101EN-3-2-Loops.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', '.DS_Store']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'README.md']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week3 - Exploratory Data Analysis', 'Scatter Plot.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week3 - Exploratory Data Analysis', 'Bar Chart.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week3 - Exploratory Data Analysis', 'exploratory_data_analysis1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week3 - Exploratory Data Analysis', 'Box Plot.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week3 - Exploratory Data Analysis', 'Combination Chart.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week3 - Exploratory Data Analysis', 'Line Chart.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week5 - Model Evaluation', 'model_evaluation_and_refinement.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week1 - Datasets', 'datasets.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week2 - Data Wrangling', 'mean-median-mode-and-range.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week2 - Data Wrangling', 'data_wrangling.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week2 - Data Wrangling', 'cosmological-natural-selection.jpg']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week2 - Data Wrangling', 'normalization.png']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week4 - Model Development', 'simple-linier-regression-11-728.jpg']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week4 - Model Development', 'Multiple Linear Regression.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week4 - Model Development', 'Linear Regression.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week4 - Model Development', 'Polynomial regression.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week4 - Model Development', 'model_development.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Open Source tools for Data Science', '.DS_Store']
['Applied-Data-Science-Specialization-IBM', 'IBM - Open Source tools for Data Science', 'README.md']
['Applied-Data-Science-Specialization-IBM', 'IBM - Open Source tools for Data Science', 'week1- Network Labs and Jupyter', 'Network Labs.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Open Source tools for Data Science', 'project', 'final.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Open Source tools for Data Science', 'week2- Apache Zeppelin Notebooks and RStudio IDE', 'map_new_york_city.R']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', '.DS_Store']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'README.md']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week4- Assignment', 'Chicago Public Schools.csv']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week4- Assignment', 'Working with a real world data-set using SQL and Python.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week4- Assignment', 'Chicago Crime Data.csv']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week4- Assignment', 'Chicago Socioeconomic Indicators.csv']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week4- Assignment', 'Notebook for Peer Assignment.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week4- Assignment', 'Working with real-world data sets.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week2- Advanced SQL', 'Additional Information on Keys and Constraints.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week2- Advanced SQL', 'Built-in Functions, Dates, Timestamps.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week2- Advanced SQL', '.DS_Store']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week2- Advanced SQL', 'Difference between Primary and Foreign Key in Database.png']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week2- Advanced SQL', 'Working with Multiple Tables.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week2- Advanced SQL', 'PETSALE-CREATE.sql']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week2- Advanced SQL', 'Sub-Queries and Nested Selects.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week2- Advanced SQL', 'PETSALE-FUNCTIONS.sql']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week2- Advanced SQL', 'lab', 'JobsHistory.csv']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week2- Advanced SQL', 'lab', 'Module4_Queries_v4.sql.txt']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week2- Advanced SQL', 'lab', 'Departments.csv']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week2- Advanced SQL', 'lab', 'Jobs.csv']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week2- Advanced SQL', 'lab', 'Locations.csv']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week2- Advanced SQL', 'lab', 'Week2Lab1v4-RA.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week2- Advanced SQL', 'lab', 'Script_Create_Tables.sql']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week2- Advanced SQL', 'lab', 'Module4_Queries_v4.sql']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week2- Advanced SQL', 'lab', 'Employees.csv']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week3- Accessing Databases using Python', 'Lab2v2JOINsolution.sql.txt']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week3- Accessing Databases using Python', 'Access DB2 on Cloud using Python.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week3- Accessing Databases using Python', 'Lab2v2JOINsolution.sql']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week3- Accessing Databases using Python', 'Analyzing a real world data-set with SQL and Python.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week3- Accessing Databases using Python', 'Lab2v3-JOIN-RA.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week3- Accessing Databases using Python', 'Connect to Db2 database on Cloud using Python.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week3- Accessing Databases using Python', 'Accessing Databases with SQL Magic.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week3- Accessing Databases using Python', 'Create-Db2-Service-Credentials.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week1- Databases and SQL', 'CREATE and DROP tables.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week1- Databases and SQL', 'terms.jpg']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week1- Databases and SQL', 'tuple_record.jpg']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week1- Databases and SQL', 'Lab2-solution-Script.sql.txt']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week1- Databases and SQL', 'Count, Distinct, Limit.pdf']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week1- Databases and SQL', 'variables-and-tables-14-728.jpg']

['Applied-Data-Science-Specialization-IBM', 'IBM - Data Visualization with Python', 'week3 - Advanced Visualizations and Geospatial Data', 'Waffle-Charts-Word-Clouds-and-Regression-Plots-py-v2.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Visualization with Python', 'week3 - Advanced Visualizations and Geospatial Data', 'Generating-Maps-in-Python-py-v2.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Visualization with Python', 'week1 - Data Visualization Tools', 'Matplotlib architecture.png']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Visualization with Python', 'week1 - Data Visualization Tools', 'Introduction-to-Matplotlib-and-Line-Plots-py-v2.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Visualization with Python', 'week1 - Data Visualization Tools', 'magic_func.svg']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Visualization with Python', 'week2 - Basic and Specialized Visualization Tools', 'box-plot-explained.gif']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Visualization with Python', 'week2 - Basic and Specialized Visualization Tools', 'area-chart-examle.png']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Visualization with Python', 'week2 - Basic and Specialized Visualization Tools', 'Pie-Charts-Box-Plots-Scatter-Plots-and-Bubble-Plots-py-v2.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Visualization with Python', 'week2 - Basic and Specialized Visualization Tools', 'Area-Plots-Histograms-and-Bar-Charts-py-v2.0.ipynb']

In [42]:
import os 

str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"
def listDir(dir):
    file_names = os.listdir(dir)
    for file_name in file_names:
        print("File Name: " + file_name)
        print("Folder Path: " + os.path.abspath(os.path.join(dir, file_name)), sep='\n')
        
if __name__ == '__main__':
    listDir(str)

File Name: .DS_Store
Folder Path: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/.DS_Store
File Name: Machine-Learning-AtoZ
Folder Path: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ
File Name: Applied-Data-Science-Specialization-IBM
Folder Path: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM

In [43]:
import os
str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"
files = []

for r, d, f in os.walk(str):
    for file in f:
        if '.ipynb' in file:
            current = os.path.join(r, file)
            row = os.path.relpath(current, str).split(os.sep)
            print(row)

['Machine-Learning-AtoZ', '01. Data Preprocessing', 'Data Preprocessing_G.ipynb']
['Machine-Learning-AtoZ', '02. Regression', '01. Simple_Linear_Regression', 'Simple LinearRegression_G.ipynb']
['Machine-Learning-AtoZ', '02. Regression', '02. Multiple_Linear_Regression', 'Multiple_Linear_Regression_G.ipynb']
['Machine-Learning-AtoZ', '02. Regression', '04. Support Vector Regression', 'Support_Vector_Regression-(SVR)_G.ipynb']
['Machine-Learning-AtoZ', '02. Regression', '05. Decision Tree Regression', 'Decision-Tree_Regression_G.ipynb']
['Machine-Learning-AtoZ', '02. Regression', '03. Polynomial Regression', 'Polynomial_Linear_Regression_G.ipynb']
['Machine-Learning-AtoZ', '03. Classification', '02. K-Nearest_Neighbors', 'K-Nearest-Neighbor_(KNN)_Classifier_G.ipynb']
['Machine-Learning-AtoZ', '03. Classification', '01. Logistic_Regression', 'Classification-Logistic_Regression_G.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week4- Clustering', 'Clus-DBSCN-weather-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week4- Clustering', 'Clus-Hierarchical-Cars-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week4- Clustering', 'Clus-K-Means-Customer-Seg-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'final-project', 'final-solution.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'final-project', 'final project.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week5- Recommender Systems', 'RecSys-Content-Based-movies-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week5- Recommender Systems', 'RecSys-Collaborative-Filtering-movies-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week3- Classification', 'Clas-K-Nearest-neighbors-CustCat-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week3- Classification', 'Clas-Decision-Trees-drug-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week3- Classification', '.ipynb_checkpoints', 'Clas-K-Nearest-neighbors-CustCat-py-v1-checkpoint.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week2- Regression', 'Reg-Polynomial-Regression-Co2-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week2- Regression', 'Reg-NoneLinearRegression-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week2- Regression', 'Reg-Mulitple-Linear-Regression-Co2-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Machine Learning with Python', 'week2- Regression', 'Reg-Simple-Linear-Regression-Co2-py-v1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Science Methodology', 'week2- From Understanding to Preparation and From Modelin to Evaluation', 'From-Modeling-to-Evaluation-v2.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Science Methodology', 'week2- From Understanding to Preparation and From Modelin to Evaluation', 'From-Understanding-to-Preparation-v2.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Science Methodology', 'week1- From Problem to Approach and From Requirements to Collection', 'From-Problem-to-Approach-v2.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Science Methodology', 'week1- From Problem to Approach and From Requirements to Collection', 'From-Requirements-to-Collection-v2.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'capstone-project', 'capstone-project.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'module3', 'Clustering-k-means-py-v1.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'module3', 'Neighborhoods-New-York-py-v1.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'module3', 'project', 'Segmenting and Clustering Neighborhoods in Toronto.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'module3', 'project', 'Segmenting and Clustering Neighborhoods with Coordinates.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'module3', 'project', 'Segmenting and Clustering Neighborhoods Final.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'module2', 'Foursquare-API-py-v1.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Applied Data Science Capstone Project', 'module1', 'assignment1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week4- Working with Data in Python', 'PY0101EN-5-1-Numpy1D.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week4- Working with Data in Python', 'PY0101EN-4-2-WriteFile.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week4- Working with Data in Python', 'PY0101EN-5-2-Numpy2D.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week4- Working with Data in Python', 'PY0101EN-4-1-ReadFile.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week5- Fake Album Cover Game', 'project.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week2- Python Data Structures', 'PY0101EN-2-2-Lists.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week2- Python Data Structures', 'PY0101EN-2-1-Tuples.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week2- Python Data Structures', 'PY0101EN-2-4-Sets.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week2- Python Data Structures', 'PY0101EN-2-3-Dictionaries.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week1- Python', 'PY0101EN-1-2-Strings.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week1- Python', 'PY0101EN-1-1-Types.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week3- Python Programming', 'PY0101EN-3-3-Functions.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week3- Python Programming', 'PY0101EN-3-4-Classes.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week3- Python Programming', 'PY0101EN-3-1-Conditions.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Python for Data Science', 'week3- Python Programming', 'PY0101EN-3-2-Loops.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week3 - Exploratory Data Analysis', 'exploratory_data_analysis1.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week5 - Model Evaluation', 'model_evaluation_and_refinement.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week1 - Datasets', 'datasets.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week2 - Data Wrangling', 'data_wrangling.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Analysis with Python', 'week4 - Model Development', 'model_development.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Open Source tools for Data Science', 'project', 'final.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week4- Assignment', 'Working with a real world data-set using SQL and Python.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week4- Assignment', 'Notebook for Peer Assignment.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week3- Accessing Databases using Python', 'Access DB2 on Cloud using Python.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week3- Accessing Databases using Python', 'Analyzing a real world data-set with SQL and Python.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week3- Accessing Databases using Python', 'Connect to Db2 database on Cloud using Python.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Databases and SQL for Data Science', 'week3- Accessing Databases using Python', 'Accessing Databases with SQL Magic.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Visualization with Python', 'week3 - Advanced Visualizations and Geospatial Data', 'Waffle-Charts-Word-Clouds-and-Regression-Plots-py-v2.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Visualization with Python', 'week3 - Advanced Visualizations and Geospatial Data', 'Generating-Maps-in-Python-py-v2.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Visualization with Python', 'week1 - Data Visualization Tools', 'Introduction-to-Matplotlib-and-Line-Plots-py-v2.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Visualization with Python', 'week2 - Basic and Specialized Visualization Tools', 'Pie-Charts-Box-Plots-Scatter-Plots-and-Bubble-Plots-py-v2.0.ipynb']
['Applied-Data-Science-Specialization-IBM', 'IBM - Data Visualization with Python', 'week2 - Basic and Specialized Visualization Tools', 'Area-Plots-Histograms-and-Bar-Charts-py-v2.0.ipynb']

In [44]:
import os

thisdir = '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/'
for r, d, f in os.walk(thisdir):
    for file in f:
        if ".py" in file:
            print(os.path.join(r, file))

In [45]:
import os

In [46]:
extentions = ['.ipynb']
str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"

def get_file_list(root_dir, E):
    file_list =[]
    counter = 1
    
    for p, d, f in os.walk(root_dir):
        for filename in f:
            
            if any(ext in filename for ext in E):
                file_list.append(os.path.join(p, filename))
                counter += 1

    return file_list

In [47]:
all_list = get_file_list(str, extentions)

In [48]:
all_list

['/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/01. Data Preprocessing/Data Preprocessing_G.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/01. Simple_Linear_Regression/Simple LinearRegression_G.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/02. Multiple_Linear_Regression/Multiple_Linear_Regression_G.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/04. Support Vector Regression/Support_Vector_Regression-(SVR)_G.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/05. Decision Tree Regression/Decision-Tree_Regression_G.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/03. Polynomial Regression/Polynomial_Linear_Regression_G.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/02. K-Nearest_Neighbors/K-Nearest-Neighbor_(KNN)_Classifier_G.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/01. Logistic_Regression/Classification-Logistic_Regression_G.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week4- Clustering/Clus-DBSCN-weather-py-v1.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week4- Clustering/Clus-Hierarchical-Cars-py-v1.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week4- Clustering/Clus-K-Means-Customer-Seg-py-v1.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/final-project/final-solution.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/final-project/final project.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week5- Recommender Systems/RecSys-Content-Based-movies-py-v1.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week5- Recommender Systems/RecSys-Collaborative-Filtering-movies-py-v1.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification/Clas-K-Nearest-neighbors-CustCat-py-v1.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification/Clas-Decision-Trees-drug-py-v1.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification/.ipynb_checkpoints/Clas-K-Nearest-neighbors-CustCat-py-v1-checkpoint.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression/Reg-Polynomial-Regression-Co2-py-v1.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression/Reg-NoneLinearRegression-py-v1.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression/Reg-Mulitple-Linear-Regression-Co2-py-v1.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression/Reg-Simple-Linear-Regression-Co2-py-v1.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week2- From Understanding to Preparation and From Modelin to Evaluation/From-Modeling-to-Evaluation-v2.0.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week2- From Understanding to Preparation and From Modelin to Evaluation/From-Understanding-to-Preparation-v2.0.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week1- From Problem to Approach and From Requirements to Collection/From-Problem-to-Approach-v2.0.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week1- From Problem to Approach and From Requirements to Collection/From-Requirements-to-Collection-v2.0.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/capstone-project/capstone-project.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/Clustering-k-means-py-v1.0.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/Neighborhoods-New-York-py-v1.0.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/project/Segmenting and Clustering Neighborhoods in Toronto.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/project/Segmenting and Clustering Neighborhoods with Coordinates.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/project/Segmenting and Clustering Neighborhoods Final.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module2/Foursquare-API-py-v1.0.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module1/assignment1.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python/PY0101EN-5-1-Numpy1D.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python/PY0101EN-4-2-WriteFile.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python/PY0101EN-5-2-Numpy2D.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python/PY0101EN-4-1-ReadFile.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week5- Fake Album Cover Game/project.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures/PY0101EN-2-2-Lists.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures/PY0101EN-2-1-Tuples.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures/PY0101EN-2-4-Sets.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures/PY0101EN-2-3-Dictionaries.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week1- Python/PY0101EN-1-2-Strings.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week1- Python/PY0101EN-1-1-Types.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming/PY0101EN-3-3-Functions.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming/PY0101EN-3-4-Classes.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming/PY0101EN-3-1-Conditions.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming/PY0101EN-3-2-Loops.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week3 - Exploratory Data Analysis/exploratory_data_analysis1.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week5 - Model Evaluation/model_evaluation_and_refinement.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets/datasets.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week2 - Data Wrangling/data_wrangling.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week4 - Model Development/model_development.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/project/final.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week4- Assignment/Working with a real world data-set using SQL and Python.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week4- Assignment/Notebook for Peer Assignment.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python/Access DB2 on Cloud using Python.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python/Analyzing a real world data-set with SQL and Python.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python/Connect to Db2 database on Cloud using Python.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python/Accessing Databases with SQL Magic.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week3 - Advanced Visualizations and Geospatial Data/Waffle-Charts-Word-Clouds-and-Regression-Plots-py-v2.0.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week3 - Advanced Visualizations and Geospatial Data/Generating-Maps-in-Python-py-v2.0.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week1 - Data Visualization Tools/Introduction-to-Matplotlib-and-Line-Plots-py-v2.0.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week2 - Basic and Specialized Visualization Tools/Pie-Charts-Box-Plots-Scatter-Plots-and-Bubble-Plots-py-v2.0.ipynb',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week2 - Basic and Specialized Visualization Tools/Area-Plots-Histograms-and-Bar-Charts-py-v2.0.ipynb']

In [49]:
len(all_list)

66

In [50]:
def get_folder_list(root_dir):
    folder_list = []
    count = 1
    
    for p, d, f in os.walk(root_dir):
        for folder in d:
            folder_list.append(os.path.join(p, folder))
            count += 1
    return folder_list

In [51]:
all_list_folder = get_folder_list(str)

In [52]:
all_list_folder

['/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/01. Data Preprocessing',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/01. Simple_Linear_Regression',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/02. Multiple_Linear_Regression',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/04. Support Vector Regression',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/06. Random Forest Regression',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/05. Decision Tree Regression',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/03. Polynomial Regression',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/02. K-Nearest_Neighbors',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/01. Logistic_Regression',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week4- Clustering',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/final-project',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week1- Machine Learning',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week5- Recommender Systems',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification/.ipynb_checkpoints',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week2- From Understanding to Preparation and From Modelin to Evaluation',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week1- From Problem to Approach and From Requirements to Collection',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week3- From Deployment to Feedback',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/capstone-project',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module2',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module1',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/project',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week5- Fake Album Cover Game',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week1- Python',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week3 - Exploratory Data Analysis',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week5 - Model Evaluation',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week2 - Data Wrangling',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week4 - Model Development',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets/.ipynb_checkpoints',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/week1- Network Labs and Jupyter',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/project',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/week2- Apache Zeppelin Notebooks and RStudio IDE',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week4- Assignment',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week2- Advanced SQL',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week1- Databases and SQL',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week2- Advanced SQL/lab',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week3 - Advanced Visualizations and Geospatial Data',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week1 - Data Visualization Tools',
 '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week2 - Basic and Specialized Visualization Tools']

In [53]:
len(all_list_folder)

58

In [1]:
import os

In [2]:
str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"
def list_files(root_dir, filetype):
    file_name_list = []
    count_file = 1
    for p, d, f in os.walk(root_dir):
        for filename in f:
            if filename.lower().endswith(filetype.lower()):
                file_name_list.append(os.path.join(filename))
                count_file += 1
    return file_name_list

In [3]:
all_file_name = list_files(str, '.ipynb')

In [4]:
all_file_name

['Course 3 - Week 1 - Exercise-answer.ipynb',
 'Data Preprocessing_G.ipynb',
 'Simple LinearRegression_G.ipynb',
 'Multiple_Linear_Regression_G.ipynb',
 'Support_Vector_Regression-(SVR)_G.ipynb',
 'Decision-Tree_Regression_G.ipynb',
 'Polynomial_Linear_Regression_G.ipynb',
 'K-Nearest-Neighbor_(KNN)_Classifier_G.ipynb',
 'Classification-Logistic_Regression_G.ipynb',
 'Clus-DBSCN-weather-py-v1.ipynb',
 'Clus-Hierarchical-Cars-py-v1.ipynb',
 'Clus-K-Means-Customer-Seg-py-v1.ipynb',
 'final-solution.ipynb',
 'final project.ipynb',
 'RecSys-Content-Based-movies-py-v1.ipynb',
 'RecSys-Collaborative-Filtering-movies-py-v1.ipynb',
 'Clas-K-Nearest-neighbors-CustCat-py-v1.ipynb',
 'Clas-Decision-Trees-drug-py-v1.ipynb',
 'Clas-K-Nearest-neighbors-CustCat-py-v1-checkpoint.ipynb',
 'Reg-Polynomial-Regression-Co2-py-v1.ipynb',
 'Reg-NoneLinearRegression-py-v1.ipynb',
 'Reg-Mulitple-Linear-Regression-Co2-py-v1.ipynb',
 'Reg-Simple-Linear-Regression-Co2-py-v1.ipynb',
 'From-Modeling-to-Evaluation-v2.0.ipynb',
 'From-Understanding-to-Preparation-v2.0.ipynb',
 'From-Problem-to-Approach-v2.0.ipynb',
 'From-Requirements-to-Collection-v2.0.ipynb',
 'capstone-project.ipynb',
 'Clustering-k-means-py-v1.0.ipynb',
 'Neighborhoods-New-York-py-v1.0.ipynb',
 'Segmenting and Clustering Neighborhoods in Toronto.ipynb',
 'Segmenting and Clustering Neighborhoods with Coordinates.ipynb',
 'Segmenting and Clustering Neighborhoods Final.ipynb',
 'Foursquare-API-py-v1.0.ipynb',
 'assignment1.ipynb',
 'PY0101EN-5-1-Numpy1D.ipynb',
 'PY0101EN-4-2-WriteFile.ipynb',
 'PY0101EN-5-2-Numpy2D.ipynb',
 'PY0101EN-4-1-ReadFile.ipynb',
 'project.ipynb',
 'PY0101EN-2-2-Lists.ipynb',
 'PY0101EN-2-1-Tuples.ipynb',
 'PY0101EN-2-4-Sets.ipynb',
 'PY0101EN-2-3-Dictionaries.ipynb',
 'PY0101EN-1-2-Strings.ipynb',
 'PY0101EN-1-1-Types.ipynb',
 'PY0101EN-3-3-Functions.ipynb',
 'PY0101EN-3-4-Classes.ipynb',
 'PY0101EN-3-1-Conditions.ipynb',
 'PY0101EN-3-2-Loops.ipynb',
 'exploratory_data_analysis1.ipynb',
 'model_evaluation_and_refinement.ipynb',
 'datasets.ipynb',
 'data_wrangling.ipynb',
 'model_development.ipynb',
 'final.ipynb',
 'Working with a real world data-set using SQL and Python.ipynb',
 'Notebook for Peer Assignment.ipynb',
 'Access DB2 on Cloud using Python.ipynb',
 'Analyzing a real world data-set with SQL and Python.ipynb',
 'Connect to Db2 database on Cloud using Python.ipynb',
 'Accessing Databases with SQL Magic.ipynb',
 'Waffle-Charts-Word-Clouds-and-Regression-Plots-py-v2.0.ipynb',
 'Generating-Maps-in-Python-py-v2.0.ipynb',
 'Introduction-to-Matplotlib-and-Line-Plots-py-v2.0.ipynb',
 'Pie-Charts-Box-Plots-Scatter-Plots-and-Bubble-Plots-py-v2.0.ipynb',
 'Area-Plots-Histograms-and-Bar-Charts-py-v2.0.ipynb']

In [58]:
len(all_file_name)

66

In [59]:
import pandas as pd

In [60]:
df = pd.DataFrame(list(zip(all_list, all_file_name)), columns =['Folder_name', 'File_name'])

In [61]:
df

,Folder_name,File_name
0,/Users/sanamjankurban/Documents/Jupyter_projec...,Data Preprocessing_G.ipynb
1,/Users/sanamjankurban/Documents/Jupyter_projec...,Simple LinearRegression_G.ipynb
2,/Users/sanamjankurban/Documents/Jupyter_projec...,Multiple_Linear_Regression_G.ipynb
3,/Users/sanamjankurban/Documents/Jupyter_projec...,Support_Vector_Regression-(SVR)_G.ipynb
4,/Users/sanamjankurban/Documents/Jupyter_projec...,Decision-Tree_Regression_G.ipynb
5,/Users/sanamjankurban/Documents/Jupyter_projec...,Polynomial_Linear_Regression_G.ipynb
6,/Users/sanamjankurban/Documents/Jupyter_projec...,K-Nearest-Neighbor_(KNN)_Classifier_G.ipynb
7,/Users/sanamjankurban/Documents/Jupyter_projec...,Classification-Logistic_Regression_G.ipynb
8,/Users/sanamjankurban/Documents/Jupyter_projec...,Clus-DBSCN-weather-py-v1.ipynb
9,/Users/sanamjankurban/Documents/Jupyter_projec...,Clus-Hierarchical-Cars-py-v1.ipynb
10,/Users/sanamjankurban/Documents/Jupyter_projec...,Clus-K-Means-Customer-Seg-py-v1.ipynb
11,/Users/sanamjankurban/Documents/Jupyter_projec...,final-solution.ipynb
12,/Users/sanamjankurban/Documents/Jupyter_projec...,final project.ipynb
13,/Users/sanamjankurban/Documents/Jupyter_projec...,RecSys-Content-Based-movies-py-v1.ipynb
14,/Users/sanamjankurban/Documents/Jupyter_projec...,RecSys-Collaborative-Filtering-movies-py-v1.ipynb
15,/Users/sanamjankurban/Documents/Jupyter_projec...,Clas-K-Nearest-neighbors-CustCat-py-v1.ipynb
16,/Users/sanamjankurban/Documents/Jupyter_projec...,Clas-Decision-Trees-drug-py-v1.ipynb
17,/Users/sanamjankurban/Documents/Jupyter_projec...,Clas-K-Nearest-neighbors-CustCat-py-v1-checkpo...
18,/Users/sanamjankurban/Documents/Jupyter_projec...,Reg-Polynomial-Regression-Co2-py-v1.ipynb
19,/Users/sanamjankurban/Documents/Jupyter_projec...,Reg-NoneLinearRegression-py-v1.ipynb
20,/Users/sanamjankurban/Documents/Jupyter_projec...,Reg-Mulitple-Linear-Regression-Co2-py-v1.ipynb
21,/Users/sanamjankurban/Documents/Jupyter_projec...,Reg-Simple-Linear-Regression-Co2-py-v1.ipynb
22,/Users/sanamjankurban/Documents/Jupyter_projec...,From-Modeling-to-Evaluation-v2.0.ipynb
23,/Users/sanamjankurban/Documents/Jupyter_projec...,From-Understanding-to-Preparation-v2.0.ipynb
24,/Users/sanamjankurban/Documents/Jupyter_projec...,From-Problem-to-Approach-v2.0.ipynb
25,/Users/sanamjankurban/Documents/Jupyter_projec...,From-Requirements-to-Collection-v2.0.ipynb
26,/Users/sanamjankurban/Documents/Jupyter_projec...,capstone-project.ipynb
27,/Users/sanamjankurban/Documents/Jupyter_projec...,Clustering-k-means-py-v1.0.ipynb
28,/Users/sanamjankurban/Documents/Jupyter_projec...,Neighborhoods-New-York-py-v1.0.ipynb
29,/Users/sanamjankurban/Documents/Jupyter_projec...,Segmenting and Clustering Neighborhoods in Tor...
...,...,...
36,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-5-2-Numpy2D.ipynb
37,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-4-1-ReadFile.ipynb
38,/Users/sanamjankurban/Documents/Jupyter_projec...,project.ipynb
39,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-2-2-Lists.ipynb
40,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-2-1-Tuples.ipynb
41,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-2-4-Sets.ipynb
42,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-2-3-Dictionaries.ipynb
43,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-1-2-Strings.ipynb
44,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-1-1-Types.ipynb
45,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-3-3-Functions.ipynb
46,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-3-4-Classes.ipynb
47,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-3-1-Conditions.ipynb
48,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-3-2-Loops.ipynb
49,/Users/sanamjankurban/Documents/Jupyter_projec...,exploratory_data_analysis1.ipynb
50,/Users/sanamjankurban/Documents/Jupyter_projec...,model_evaluation_and_refinement.ipynb
51,/Users/sanamjankurban/Documents/Jupyter_projec...,datasets.ipynb
52,/Users/sanamjankurban/Documents/Jupyter_projec...,data_wrangling.ipynb
53,/Users/sanamjankurban/Documents/Jupyter_projec...,model_development.ipynb
54,/Users/sanamjankurban/Documents/Jupyter_projec...,final.ipynb
55,/Users/sanamjankurban/Documents/Jupyter_projec...,Working with a real world data-set using SQL a...
56,/Users/sanamjankurban/Documents/Jupyter_projec...,Notebook for Peer Assignment.ipynb
57,/Users/sanamjankurban/Documents/Jupyter_projec...,Access DB2 on Cloud using Python.ipynb
58,/Users/sanamjankurban/Documents/Jupyter_projec...,Analyzing a real world data-set with SQL and P...
59,/Users/sanamjankurban/Documents/Jupyter_projec...,Connect to Db2 database on Cloud using Python....
60,/Users/sanamjankurban/Documents/Jupyter_projec...,Accessing Databases with SQL Magic.ipynb
61,/Users/sanamjankurban/Documents/Jupyter_projec...,Waffle-Charts-Word-Clouds-and-Regression-Plots...
62,/Users/sanamjankurban/Documents/Jupyter_projec...,Generating-Maps-in-Python-py-v2.0.ipynb
63,/Users/sanamjankurban/Documents/Jupyter_projec...,Introduction-to-Matplotlib-and-Line-Plots-py-v...
64,/Users/sanamjankurban/Documents/Jupyter_projec...,Pie-Charts-Box-Plots-Scatter-Plots-and-Bubble-...
65,/Users/sanamjankurban/Documents/Jupyter_projec...,Area-Plots-Histograms-and-Bar-Charts-py-v2.0.i...

In [62]:
df.head(5)

,Folder_name,File_name
0,/Users/sanamjankurban/Documents/Jupyter_projec...,Data Preprocessing_G.ipynb
1,/Users/sanamjankurban/Documents/Jupyter_projec...,Simple LinearRegression_G.ipynb
2,/Users/sanamjankurban/Documents/Jupyter_projec...,Multiple_Linear_Regression_G.ipynb
3,/Users/sanamjankurban/Documents/Jupyter_projec...,Support_Vector_Regression-(SVR)_G.ipynb
4,/Users/sanamjankurban/Documents/Jupyter_projec...,Decision-Tree_Regression_G.ipynb

In [63]:
data_list = {1, 2}
print(data_list)

{1, 2}

In [64]:
a= 'sanam'
b= 'gulum'
list_data={"my name:": a, "her name:": b}
print(list_data)

{'my name:': 'sanam', 'her name:': 'gulum'}

In [65]:
list_data = {}

a='gul'
b='gulum'
if a == 'gul' and b == '':
    list_data = {a, b}
    print(list_data)
elif a == 'gul':
    list_data = {a}
    print(list_data)
elif b == 'gulum':
    list_data = {b}
    print(list_data)
else: print("no data")

{'gul'}

In [66]:
import pandas as pd
name = ['a', 'b', 'c', 'd']
mo_z =[-4.01, 2.11, 2.43, -2]
mt_z =[0.11, 4.21, -3.55, -5.21]

list_of_data = list(zip(name, mo_z, mt_z))
list_of_data

[('a', -4.01, 0.11), ('b', 2.11, 4.21), ('c', 2.43, -3.55), ('d', -2, -5.21)]

In [67]:
df = pd.DataFrame(list_of_data, columns=['name', 'mo_z', 'mt_z'])
df

  name  mo_z  mt_z
0    a -4.01  0.11
1    b  2.11  4.21
2    c  2.43 -3.55
3    d -2.00 -5.21

In [68]:
df1 = df[(df['mo_z'] > 3) | (df['mo_z'] < -3)]

In [69]:
df1

  name  mo_z  mt_z
0    a -4.01  0.11

In [70]:
df2 = df[(df['mt_z'] > 3) | (df['mt_z'] < -3)]

In [71]:
df2

  name  mo_z  mt_z
1    b  2.11  4.21
2    c  2.43 -3.55
3    d -2.00 -5.21

In [72]:
len(df1.index)

1

In [73]:
list_data = {}

if len(df1.index) > 0 and len(df2.index) > 0:
    a = df1[['name', 'mo_z', 'mt_z']]
    b = df2[['name', 'mo_z', 'mt_z']]
    list_data = {'like': a, 'look': b}
    print(list_data)
elif len(df1.index) > 0:
    a = df1[['name', 'mo_z', 'mt_z']]
    list_data = {'like': a}
    print(list_data)
elif len(df2.index) > 0:
    b = df2[['name', 'mo_z', 'mt_z']]
    list_data = {'look': b}
    print(list_data)
else: print("no data")

{'like':   name  mo_z  mt_z
0    a -4.01  0.11, 'look':   name  mo_z  mt_z
1    b  2.11  4.21
2    c  2.43 -3.55
3    d -2.00 -5.21}

In [74]:
import os

str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"
def read_veri():
    folder_list = []
    count_veri = 1
    
    for p, d, f in os.walk(str):
        for folder_dir in d:
            folder_list.append(os.path.join(p, folder_dir))
            count_veri += 1
    return folder_list
all_list = read_veri()
print(all_list)

['/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/01. Data Preprocessing', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/01. Simple_Linear_Regression', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/02. Multiple_Linear_Regression', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/04. Support Vector Regression', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/06. Random Forest Regression', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/05. Decision Tree Regression', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/03. Polynomial Regression', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/02. K-Nearest_Neighbors', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/01. Logistic_Regression', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week4- Clustering', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/final-project', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week1- Machine Learning', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week5- Recommender Systems', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification/.ipynb_checkpoints', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week2- From Understanding to Preparation and From Modelin to Evaluation', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week1- From Problem to Approach and From Requirements to Collection', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week3- From Deployment to Feedback', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/capstone-project', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module2', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module1', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/project', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week5- Fake Album Cover Game', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week1- Python', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week3 - Exploratory Data Analysis', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week5 - Model Evaluation', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week2 - Data Wrangling', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week4 - Model Development', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets/.ipynb_checkpoints', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/week1- Network Labs and Jupyter', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/project', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/week2- Apache Zeppelin Notebooks and RStudio IDE', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week4- Assignment', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week2- Advanced SQL', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week1- Databases and SQL', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week2- Advanced SQL/lab', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week3 - Advanced Visualizations and Geospatial Data', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week1 - Data Visualization Tools', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week2 - Basic and Specialized Visualization Tools']

In [75]:
from pathlib import Path

str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"
basepath = Path(str)
for entry in basepath.iterdir():
    if entry.is_dir():
        print(entry.name)

Machine-Learning-AtoZ
Applied-Data-Science-Specialization-IBM

In [76]:
import os
str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"

for p, d, f in os.walk(str):
    print(f'Found director: {p}')
    for f_name in f:
        print(f_name)

Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/
.DS_Store
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ
.DS_Store
README.md
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/01. Data Preprocessing
Data Preprocessing_G.ipynb
Data.csv
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression
.DS_Store
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/01. Simple_Linear_Regression
Salary_Data.csv
Simple LinearRegression_G.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/02. Multiple_Linear_Regression
50_Startups.csv
Multiple_Linear_Regression_G.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/04. Support Vector Regression
Support_Vector_Regression-(SVR)_G.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/06. Random Forest Regression
Random Forest Regression
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/05. Decision Tree Regression
Decision-Tree_Regression_G.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/03. Polynomial Regression
Polynomial_Linear_Regression_G.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification
.DS_Store
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/02. K-Nearest_Neighbors
K-Nearest-Neighbor_(KNN)_Classifier_G.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/01. Logistic_Regression
Classification-Logistic_Regression_G.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM
.DS_Store
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python
.DS_Store
README.md
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week4- Clustering
Clus-DBSCN-weather-py-v1.ipynb
Clus-Hierarchical-Cars-py-v1.ipynb
Clus-K-Means-Customer-Seg-py-v1.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/final-project
final-solution.ipynb
final project.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week1- Machine Learning
cheat-sheet.png
supervised-vs-unsupervised.png
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week5- Recommender Systems
RecSys-Content-Based-movies-py-v1.ipynb
memory-based-vs-model-based.png
RecSys-Collaborative-Filtering-movies-py-v1.ipynb
challenges-of-collaboration.png
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification
Clas-K-Nearest-neighbors-CustCat-py-v1.ipynb
entropy-and-information-gain.png
knn.jpg
Clas-Decision-Trees-drug-py-v1.ipynb
linear_vs_logistic_regression.jpg
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification/.ipynb_checkpoints
Clas-K-Nearest-neighbors-CustCat-py-v1-checkpoint.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression
linear-vs-nonlinear.jpg
Reg-Polynomial-Regression-Co2-py-v1.ipynb
accuracy-vs-generalization.jpg
Reg-NoneLinearRegression-py-v1.ipynb
Reg-Mulitple-Linear-Regression-Co2-py-v1.ipynb
Reg-Simple-Linear-Regression-Co2-py-v1.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology
analytics-chart.png
.DS_Store
data-method.jpg
data-science-process.png
README.md
data-science-salon-clustering-a-top-down-and-bottom-up-approach.jpg
sum.png
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week2- From Understanding to Preparation and From Modelin to Evaluation
From-Modeling-to-Evaluation-v2.0.ipynb
From-Understanding-to-Preparation-v2.0.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week1- From Problem to Approach and From Requirements to Collection
From-Problem-to-Approach-v2.0.ipynb
From-Requirements-to-Collection-v2.0.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week3- From Deployment to Feedback
Data-Science-Tools-for-Email-Analysis-Research-Guide.pdf
Final-Assignment.docx
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project
.DS_Store
README.md
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/capstone-project
data.zip
project-notebook.pdf
README.md
capstone-project.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3
Clustering-k-means-py-v1.0.ipynb
.DS_Store
Neighborhoods-New-York-py-v1.0.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/project
Segmenting and Clustering Neighborhoods in Toronto.ipynb
Segmenting and Clustering Neighborhoods with Coordinates.ipynb
Segmenting and Clustering Neighborhoods Final.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module2
Foursquare-API-py-v1.0.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module1
assignment1.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science
.DS_Store
README.md
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python
PY0101EN-5-1-Numpy1D.ipynb
PY0101EN-4-2-WriteFile.ipynb
PY0101EN-5-2-Numpy2D.ipynb
PY0101EN-4-1-ReadFile.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week5- Fake Album Cover Game
project.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures
PY0101EN-2-2-Lists.ipynb
PY0101EN-2-1-Tuples.ipynb
PY0101EN-2-4-Sets.ipynb
PY0101EN-2-3-Dictionaries.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week1- Python
PY0101EN-1-2-Strings.ipynb
PY0101EN-1-1-Types.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming
PY0101EN-3-3-Functions.ipynb
PY0101EN-3-4-Classes.ipynb
PY0101EN-3-1-Conditions.ipynb
PY0101EN-3-2-Loops.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python
.DS_Store
README.md
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week3 - Exploratory Data Analysis
Scatter Plot.pdf
Bar Chart.pdf
exploratory_data_analysis1.ipynb
Box Plot.pdf
Combination Chart.pdf
Line Chart.pdf
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week5 - Model Evaluation
model_evaluation_and_refinement.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets
datasets.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets/.ipynb_checkpoints
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week2 - Data Wrangling
mean-median-mode-and-range.pdf
data_wrangling.ipynb
cosmological-natural-selection.jpg
normalization.png
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week4 - Model Development
simple-linier-regression-11-728.jpg
Multiple Linear Regression.pdf
Linear Regression.pdf
Polynomial regression.pdf
model_development.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science
.DS_Store
README.md
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/week1- Network Labs and Jupyter
Network Labs.pdf
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/project
final.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/week2- Apache Zeppelin Notebooks and RStudio IDE
map_new_york_city.R
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science
.DS_Store
README.md
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week4- Assignment
Chicago Public Schools.csv
Working with a real world data-set using SQL and Python.ipynb
Chicago Crime Data.csv
Chicago Socioeconomic Indicators.csv
Notebook for Peer Assignment.ipynb
Working with real-world data sets.pdf
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week2- Advanced SQL
Additional Information on Keys and Constraints.pdf
Built-in Functions, Dates, Timestamps.pdf
.DS_Store
Difference between Primary and Foreign Key in Database.png
Working with Multiple Tables.pdf
PETSALE-CREATE.sql
Sub-Queries and Nested Selects.pdf
PETSALE-FUNCTIONS.sql
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week2- Advanced SQL/lab
JobsHistory.csv
Module4_Queries_v4.sql.txt
Departments.csv
Jobs.csv
Locations.csv
Week2Lab1v4-RA.pdf
Script_Create_Tables.sql
Module4_Queries_v4.sql
Employees.csv
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python
Lab2v2JOINsolution.sql.txt
Access DB2 on Cloud using Python.ipynb
Lab2v2JOINsolution.sql
Analyzing a real world data-set with SQL and Python.ipynb
Lab2v3-JOIN-RA.pdf
Connect to Db2 database on Cloud using Python.ipynb
Accessing Databases with SQL Magic.ipynb
Create-Db2-Service-Credentials.pdf
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week1- Databases and SQL
CREATE and DROP tables.pdf
terms.jpg
tuple_record.jpg
Lab2-solution-Script.sql.txt
Count, Distinct, Limit.pdf
variables-and-tables-14-728.jpg
SELECT statement.pdf
sql-cheat-sheet-for-data-scientists-by-tomi-mester.pdf
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python
.DS_Store
README.md
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week3 - Advanced Visualizations and Geospatial Data
Waffle-Charts-Word-Clouds-and-Regression-Plots-py-v2.0.ipynb
Generating-Maps-in-Python-py-v2.0.ipynb
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week1 - Data Visualization Tools
Matplotlib architecture.png
Introduction-to-Matplotlib-and-Line-Plots-py-v2.0.ipynb
magic_func.svg
Found director: /Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week2 - Basic and Specialized Visualization Tools
box-plot-explained.gif
area-chart-examle.png
Pie-Charts-Box-Plots-Scatter-Plots-and-Bubble-Plots-py-v2.0.ipynb
Area-Plots-Histograms-and-Bar-Charts-py-v2.0.ipynb

In [77]:
import os

str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"
def read_veri():
    folder_list = []
    count_veri = 1
    
    for p, d, f in os.walk(str):
        for folder_dir in d:
            folder_list.append(os.path.join(p, folder_dir))
            count_veri += 1
    return folder_list
all_list = read_veri()
print(*all_list, sep = "\n")
len(all_list)

/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/01. Data Preprocessing
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/01. Simple_Linear_Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/02. Multiple_Linear_Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/04. Support Vector Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/06. Random Forest Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/05. Decision Tree Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/03. Polynomial Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/02. K-Nearest_Neighbors
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/01. Logistic_Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week4- Clustering
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/final-project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week1- Machine Learning
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week5- Recommender Systems
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week2- From Understanding to Preparation and From Modelin to Evaluation
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week1- From Problem to Approach and From Requirements to Collection
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week3- From Deployment to Feedback
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/capstone-project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module2
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module1
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week5- Fake Album Cover Game
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week1- Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week3 - Exploratory Data Analysis
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week5 - Model Evaluation
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week2 - Data Wrangling
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week4 - Model Development
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets/.ipynb_checkpoints
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/week1- Network Labs and Jupyter
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/project
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/week2- Apache Zeppelin Notebooks and RStudio IDE
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week4- Assignment
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week2- Advanced SQL
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week1- Databases and SQL
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week2- Advanced SQL/lab
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week3 - Advanced Visualizations and Geospatial Data
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week1 - Data Visualization Tools
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week2 - Basic and Specialized Visualization Tools

58

In [78]:
import os
from pathlib import Path

str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"
def read_subdir():
    subdir_list = []
    root_dir = []
    counts_veri = 1
    
    for p, d, f in os.walk(str):
        for subfolder_dir in d:
            subdir_list.append(os.path.join(p, subfolder_dir))
            counts_veri += 1
    return subdir_list
all_list_subfolder = read_subdir()
print(all_list_subfolder)
len(all_list_subfolder)

['/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/01. Data Preprocessing', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/01. Simple_Linear_Regression', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/02. Multiple_Linear_Regression', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/04. Support Vector Regression', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/06. Random Forest Regression', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/05. Decision Tree Regression', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/03. Polynomial Regression', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/02. K-Nearest_Neighbors', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/01. Logistic_Regression', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week4- Clustering', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/final-project', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week1- Machine Learning', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week5- Recommender Systems', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification/.ipynb_checkpoints', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week2- From Understanding to Preparation and From Modelin to Evaluation', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week1- From Problem to Approach and From Requirements to Collection', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week3- From Deployment to Feedback', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/capstone-project', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module2', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module1', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/project', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week5- Fake Album Cover Game', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week1- Python', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week3 - Exploratory Data Analysis', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week5 - Model Evaluation', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week2 - Data Wrangling', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week4 - Model Development', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets/.ipynb_checkpoints', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/week1- Network Labs and Jupyter', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/project', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/week2- Apache Zeppelin Notebooks and RStudio IDE', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week4- Assignment', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week2- Advanced SQL', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week1- Databases and SQL', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week2- Advanced SQL/lab', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week3 - Advanced Visualizations and Geospatial Data', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week1 - Data Visualization Tools', '/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week2 - Basic and Specialized Visualization Tools']

58

In [79]:
df = pd.DataFrame(list(zip(all_list_subfolder)), columns =['Folder_name'])

In [80]:
df

                                          Folder_name
0   /Users/sanamjankurban/Documents/Jupyter_projec...
1   /Users/sanamjankurban/Documents/Jupyter_projec...
2   /Users/sanamjankurban/Documents/Jupyter_projec...
3   /Users/sanamjankurban/Documents/Jupyter_projec...
4   /Users/sanamjankurban/Documents/Jupyter_projec...
5   /Users/sanamjankurban/Documents/Jupyter_projec...
6   /Users/sanamjankurban/Documents/Jupyter_projec...
7   /Users/sanamjankurban/Documents/Jupyter_projec...
8   /Users/sanamjankurban/Documents/Jupyter_projec...
9   /Users/sanamjankurban/Documents/Jupyter_projec...
10  /Users/sanamjankurban/Documents/Jupyter_projec...
11  /Users/sanamjankurban/Documents/Jupyter_projec...
12  /Users/sanamjankurban/Documents/Jupyter_projec...
13  /Users/sanamjankurban/Documents/Jupyter_projec...
14  /Users/sanamjankurban/Documents/Jupyter_projec...
15  /Users/sanamjankurban/Documents/Jupyter_projec...
16  /Users/sanamjankurban/Documents/Jupyter_projec...
17  /Users/sanamjankurban/Documents/Jupyter_projec...
18  /Users/sanamjankurban/Documents/Jupyter_projec...
19  /Users/sanamjankurban/Documents/Jupyter_projec...
20  /Users/sanamjankurban/Documents/Jupyter_projec...
21  /Users/sanamjankurban/Documents/Jupyter_projec...
22  /Users/sanamjankurban/Documents/Jupyter_projec...
23  /Users/sanamjankurban/Documents/Jupyter_projec...
24  /Users/sanamjankurban/Documents/Jupyter_projec...
25  /Users/sanamjankurban/Documents/Jupyter_projec...
26  /Users/sanamjankurban/Documents/Jupyter_projec...
27  /Users/sanamjankurban/Documents/Jupyter_projec...
28  /Users/sanamjankurban/Documents/Jupyter_projec...
29  /Users/sanamjankurban/Documents/Jupyter_projec...
30  /Users/sanamjankurban/Documents/Jupyter_projec...
31  /Users/sanamjankurban/Documents/Jupyter_projec...
32  /Users/sanamjankurban/Documents/Jupyter_projec...
33  /Users/sanamjankurban/Documents/Jupyter_projec...
34  /Users/sanamjankurban/Documents/Jupyter_projec...
35  /Users/sanamjankurban/Documents/Jupyter_projec...
36  /Users/sanamjankurban/Documents/Jupyter_projec...
37  /Users/sanamjankurban/Documents/Jupyter_projec...
38  /Users/sanamjankurban/Documents/Jupyter_projec...
39  /Users/sanamjankurban/Documents/Jupyter_projec...
40  /Users/sanamjankurban/Documents/Jupyter_projec...
41  /Users/sanamjankurban/Documents/Jupyter_projec...
42  /Users/sanamjankurban/Documents/Jupyter_projec...
43  /Users/sanamjankurban/Documents/Jupyter_projec...
44  /Users/sanamjankurban/Documents/Jupyter_projec...
45  /Users/sanamjankurban/Documents/Jupyter_projec...
46  /Users/sanamjankurban/Documents/Jupyter_projec...
47  /Users/sanamjankurban/Documents/Jupyter_projec...
48  /Users/sanamjankurban/Documents/Jupyter_projec...
49  /Users/sanamjankurban/Documents/Jupyter_projec...
50  /Users/sanamjankurban/Documents/Jupyter_projec...
51  /Users/sanamjankurban/Documents/Jupyter_projec...
52  /Users/sanamjankurban/Documents/Jupyter_projec...
53  /Users/sanamjankurban/Documents/Jupyter_projec...
54  /Users/sanamjankurban/Documents/Jupyter_projec...
55  /Users/sanamjankurban/Documents/Jupyter_projec...
56  /Users/sanamjankurban/Documents/Jupyter_projec...
57  /Users/sanamjankurban/Documents/Jupyter_projec...

In [81]:
df.to_csv('folder.csv', index = False, header = True)

In [82]:
df_data = pd.read_csv('folder.csv')

In [83]:
df_data.head(10)

                                         Folder_name
0  /Users/sanamjankurban/Documents/Jupyter_projec...
1  /Users/sanamjankurban/Documents/Jupyter_projec...
2  /Users/sanamjankurban/Documents/Jupyter_projec...
3  /Users/sanamjankurban/Documents/Jupyter_projec...
4  /Users/sanamjankurban/Documents/Jupyter_projec...
5  /Users/sanamjankurban/Documents/Jupyter_projec...
6  /Users/sanamjankurban/Documents/Jupyter_projec...
7  /Users/sanamjankurban/Documents/Jupyter_projec...
8  /Users/sanamjankurban/Documents/Jupyter_projec...
9  /Users/sanamjankurban/Documents/Jupyter_projec...

In [84]:
import os
import time
extentions = ['.ipynb']
str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"

def get_file_list(root_dir, E):
    file_list = []
    counter = 1
    
    for p, d, f in os.walk(root_dir):
        for filename in f:
            
            if any(ext in filename for ext in E):
                fullpath = os.path.join(p, filename)
                file_name = os.path.join(filename)
                size = os.path.getsize(fullpath)
                time_file = os.path.getctime(fullpath)
                create_time = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(time_file))
                item_list = (fullpath, filename, size, create_time)
                file_list.append(item_list)
                counter += 1

    return file_list

In [85]:
all_list = get_file_list(str, extentions)

In [86]:
all_list

[('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/01. Data Preprocessing/Data Preprocessing_G.ipynb',
  'Data Preprocessing_G.ipynb',
  14316,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/01. Simple_Linear_Regression/Simple LinearRegression_G.ipynb',
  'Simple LinearRegression_G.ipynb',
  41448,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/02. Multiple_Linear_Regression/Multiple_Linear_Regression_G.ipynb',
  'Multiple_Linear_Regression_G.ipynb',
  45460,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/04. Support Vector Regression/Support_Vector_Regression-(SVR)_G.ipynb',
  'Support_Vector_Regression-(SVR)_G.ipynb',
  47978,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/05. Decision Tree Regression/Decision-Tree_Regression_G.ipynb',
  'Decision-Tree_Regression_G.ipynb',
  56654,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/03. Polynomial Regression/Polynomial_Linear_Regression_G.ipynb',
  'Polynomial_Linear_Regression_G.ipynb',
  109951,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/02. K-Nearest_Neighbors/K-Nearest-Neighbor_(KNN)_Classifier_G.ipynb',
  'K-Nearest-Neighbor_(KNN)_Classifier_G.ipynb',
  87662,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/01. Logistic_Regression/Classification-Logistic_Regression_G.ipynb',
  'Classification-Logistic_Regression_G.ipynb',
  135967,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week4- Clustering/Clus-DBSCN-weather-py-v1.ipynb',
  'Clus-DBSCN-weather-py-v1.ipynb',
  29410,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week4- Clustering/Clus-Hierarchical-Cars-py-v1.ipynb',
  'Clus-Hierarchical-Cars-py-v1.ipynb',
  26078,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week4- Clustering/Clus-K-Means-Customer-Seg-py-v1.ipynb',
  'Clus-K-Means-Customer-Seg-py-v1.ipynb',
  25883,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/final-project/final-solution.ipynb',
  'final-solution.ipynb',
  100089,
  '2021-02-18 22:37:23'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/final-project/final project.ipynb',
  'final project.ipynb',
  92987,
  '2021-02-18 22:37:23'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week5- Recommender Systems/RecSys-Content-Based-movies-py-v1.ipynb',
  'RecSys-Content-Based-movies-py-v1.ipynb',
  18443,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week5- Recommender Systems/RecSys-Collaborative-Filtering-movies-py-v1.ipynb',
  'RecSys-Collaborative-Filtering-movies-py-v1.ipynb',
  33260,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification/Clas-K-Nearest-neighbors-CustCat-py-v1.ipynb',
  'Clas-K-Nearest-neighbors-CustCat-py-v1.ipynb',
  21543,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification/Clas-Decision-Trees-drug-py-v1.ipynb',
  'Clas-Decision-Trees-drug-py-v1.ipynb',
  21086,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification/.ipynb_checkpoints/Clas-K-Nearest-neighbors-CustCat-py-v1-checkpoint.ipynb',
  'Clas-K-Nearest-neighbors-CustCat-py-v1-checkpoint.ipynb',
  21543,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression/Reg-Polynomial-Regression-Co2-py-v1.ipynb',
  'Reg-Polynomial-Regression-Co2-py-v1.ipynb',
  17624,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression/Reg-NoneLinearRegression-py-v1.ipynb',
  'Reg-NoneLinearRegression-py-v1.ipynb',
  16549,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression/Reg-Mulitple-Linear-Regression-Co2-py-v1.ipynb',
  'Reg-Mulitple-Linear-Regression-Co2-py-v1.ipynb',
  16123,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression/Reg-Simple-Linear-Regression-Co2-py-v1.ipynb',
  'Reg-Simple-Linear-Regression-Co2-py-v1.ipynb',
  18310,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week2- From Understanding to Preparation and From Modelin to Evaluation/From-Modeling-to-Evaluation-v2.0.ipynb',
  'From-Modeling-to-Evaluation-v2.0.ipynb',
  34865,
  '2021-02-18 22:37:23'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week2- From Understanding to Preparation and From Modelin to Evaluation/From-Understanding-to-Preparation-v2.0.ipynb',
  'From-Understanding-to-Preparation-v2.0.ipynb',
  30874,
  '2021-02-18 22:37:23'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week1- From Problem to Approach and From Requirements to Collection/From-Problem-to-Approach-v2.0.ipynb',
  'From-Problem-to-Approach-v2.0.ipynb',
  25799,
  '2021-02-18 22:37:23'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week1- From Problem to Approach and From Requirements to Collection/From-Requirements-to-Collection-v2.0.ipynb',
  'From-Requirements-to-Collection-v2.0.ipynb',
  13299,
  '2021-02-18 22:37:23'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/capstone-project/capstone-project.ipynb',
  'capstone-project.ipynb',
  31724,
  '2021-02-18 22:37:22'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/Clustering-k-means-py-v1.0.ipynb',
  'Clustering-k-means-py-v1.0.ipynb',
  30157,
  '2021-02-18 22:37:22'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/Neighborhoods-New-York-py-v1.0.ipynb',
  'Neighborhoods-New-York-py-v1.0.ipynb',
  38311,
  '2021-02-18 22:37:22'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/project/Segmenting and Clustering Neighborhoods in Toronto.ipynb',
  'Segmenting and Clustering Neighborhoods in Toronto.ipynb',
  25422,
  '2021-02-18 22:37:22'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/project/Segmenting and Clustering Neighborhoods with Coordinates.ipynb',
  'Segmenting and Clustering Neighborhoods with Coordinates.ipynb',
  33145,
  '2021-02-18 22:37:22'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/project/Segmenting and Clustering Neighborhoods Final.ipynb',
  'Segmenting and Clustering Neighborhoods Final.ipynb',
  511501,
  '2021-02-18 22:37:22'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module2/Foursquare-API-py-v1.0.ipynb',
  'Foursquare-API-py-v1.0.ipynb',
  45911,
  '2021-02-18 22:37:22'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module1/assignment1.ipynb',
  'assignment1.ipynb',
  1350,
  '2021-02-18 22:37:22'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python/PY0101EN-5-1-Numpy1D.ipynb',
  'PY0101EN-5-1-Numpy1D.ipynb',
  34084,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python/PY0101EN-4-2-WriteFile.ipynb',
  'PY0101EN-4-2-WriteFile.ipynb',
  11860,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python/PY0101EN-5-2-Numpy2D.ipynb',
  'PY0101EN-5-2-Numpy2D.ipynb',
  17551,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python/PY0101EN-4-1-ReadFile.ipynb',
  'PY0101EN-4-1-ReadFile.ipynb',
  15195,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week5- Fake Album Cover Game/project.ipynb',
  'project.ipynb',
  62363,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures/PY0101EN-2-2-Lists.ipynb',
  'PY0101EN-2-2-Lists.ipynb',
  23056,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures/PY0101EN-2-1-Tuples.ipynb',
  'PY0101EN-2-1-Tuples.ipynb',
  26144,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures/PY0101EN-2-4-Sets.ipynb',
  'PY0101EN-2-4-Sets.ipynb',
  18836,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures/PY0101EN-2-3-Dictionaries.ipynb',
  'PY0101EN-2-3-Dictionaries.ipynb',
  17301,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week1- Python/PY0101EN-1-2-Strings.ipynb',
  'PY0101EN-1-2-Strings.ipynb',
  27271,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week1- Python/PY0101EN-1-1-Types.ipynb',
  'PY0101EN-1-1-Types.ipynb',
  39525,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming/PY0101EN-3-3-Functions.ipynb',
  'PY0101EN-3-3-Functions.ipynb',
  31829,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming/PY0101EN-3-4-Classes.ipynb',
  'PY0101EN-3-4-Classes.ipynb',
  21977,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming/PY0101EN-3-1-Conditions.ipynb',
  'PY0101EN-3-1-Conditions.ipynb',
  28636,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming/PY0101EN-3-2-Loops.ipynb',
  'PY0101EN-3-2-Loops.ipynb',
  16167,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week3 - Exploratory Data Analysis/exploratory_data_analysis1.ipynb',
  'exploratory_data_analysis1.ipynb',
  44066,
  '2021-02-18 22:37:22'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week5 - Model Evaluation/model_evaluation_and_refinement.ipynb',
  'model_evaluation_and_refinement.ipynb',
  41924,
  '2021-02-18 22:37:23'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets/datasets.ipynb',
  'datasets.ipynb',
  17328,
  '2021-02-18 22:37:22'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week2 - Data Wrangling/data_wrangling.ipynb',
  'data_wrangling.ipynb',
  40351,
  '2021-02-18 22:37:22'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week4 - Model Development/model_development.ipynb',
  'model_development.ipynb',
  47985,
  '2021-02-18 22:37:23'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/project/final.ipynb',
  'final.ipynb',
  1981,
  '2021-02-18 22:37:24'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week4- Assignment/Working with a real world data-set using SQL and Python.ipynb',
  'Working with a real world data-set using SQL and Python.ipynb',
  20284,
  '2021-02-18 22:37:23'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week4- Assignment/Notebook for Peer Assignment.ipynb',
  'Notebook for Peer Assignment.ipynb',
  34244,
  '2021-02-18 22:37:23'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python/Access DB2 on Cloud using Python.ipynb',
  'Access DB2 on Cloud using Python.ipynb',
  15293,
  '2021-02-18 22:37:23'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python/Analyzing a real world data-set with SQL and Python.ipynb',
  'Analyzing a real world data-set with SQL and Python.ipynb',
  12066,
  '2021-02-18 22:37:23'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python/Connect to Db2 database on Cloud using Python.ipynb',
  'Connect to Db2 database on Cloud using Python.ipynb',
  7946,
  '2021-02-18 22:37:23'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python/Accessing Databases with SQL Magic.ipynb',
  'Accessing Databases with SQL Magic.ipynb',
  12155,
  '2021-02-18 22:37:23'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week3 - Advanced Visualizations and Geospatial Data/Waffle-Charts-Word-Clouds-and-Regression-Plots-py-v2.0.ipynb',
  'Waffle-Charts-Word-Clouds-and-Regression-Plots-py-v2.0.ipynb',
  58732,
  '2021-02-18 22:37:23'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week3 - Advanced Visualizations and Geospatial Data/Generating-Maps-in-Python-py-v2.0.ipynb',
  'Generating-Maps-in-Python-py-v2.0.ipynb',
  45514,
  '2021-02-18 22:37:23'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week1 - Data Visualization Tools/Introduction-to-Matplotlib-and-Line-Plots-py-v2.0.ipynb',
  'Introduction-to-Matplotlib-and-Line-Plots-py-v2.0.ipynb',
  49979,
  '2021-02-18 22:37:23'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week2 - Basic and Specialized Visualization Tools/Pie-Charts-Box-Plots-Scatter-Plots-and-Bubble-Plots-py-v2.0.ipynb',
  'Pie-Charts-Box-Plots-Scatter-Plots-and-Bubble-Plots-py-v2.0.ipynb',
  64413,
  '2021-02-18 22:37:23'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week2 - Basic and Specialized Visualization Tools/Area-Plots-Histograms-and-Bar-Charts-py-v2.0.ipynb',
  'Area-Plots-Histograms-and-Bar-Charts-py-v2.0.ipynb',
  54266,
  '2021-02-18 22:37:23')]

In [87]:
len(all_list)

66

In [88]:
import pandas as pd
df = pd.DataFrame(all_list, columns=['Folder_name', "File_name", "Size", "Datetime"])

In [89]:
df

,Folder_name,File_name,Size,Datetime
0,/Users/sanamjankurban/Documents/Jupyter_projec...,Data Preprocessing_G.ipynb,14316,2021-02-18 22:37:24
1,/Users/sanamjankurban/Documents/Jupyter_projec...,Simple LinearRegression_G.ipynb,41448,2021-02-18 22:37:24
2,/Users/sanamjankurban/Documents/Jupyter_projec...,Multiple_Linear_Regression_G.ipynb,45460,2021-02-18 22:37:24
3,/Users/sanamjankurban/Documents/Jupyter_projec...,Support_Vector_Regression-(SVR)_G.ipynb,47978,2021-02-18 22:37:24
4,/Users/sanamjankurban/Documents/Jupyter_projec...,Decision-Tree_Regression_G.ipynb,56654,2021-02-18 22:37:24
5,/Users/sanamjankurban/Documents/Jupyter_projec...,Polynomial_Linear_Regression_G.ipynb,109951,2021-02-18 22:37:24
6,/Users/sanamjankurban/Documents/Jupyter_projec...,K-Nearest-Neighbor_(KNN)_Classifier_G.ipynb,87662,2021-02-18 22:37:24
7,/Users/sanamjankurban/Documents/Jupyter_projec...,Classification-Logistic_Regression_G.ipynb,135967,2021-02-18 22:37:24
8,/Users/sanamjankurban/Documents/Jupyter_projec...,Clus-DBSCN-weather-py-v1.ipynb,29410,2021-02-18 22:37:24
9,/Users/sanamjankurban/Documents/Jupyter_projec...,Clus-Hierarchical-Cars-py-v1.ipynb,26078,2021-02-18 22:37:24
10,/Users/sanamjankurban/Documents/Jupyter_projec...,Clus-K-Means-Customer-Seg-py-v1.ipynb,25883,2021-02-18 22:37:24
11,/Users/sanamjankurban/Documents/Jupyter_projec...,final-solution.ipynb,100089,2021-02-18 22:37:23
12,/Users/sanamjankurban/Documents/Jupyter_projec...,final project.ipynb,92987,2021-02-18 22:37:23
13,/Users/sanamjankurban/Documents/Jupyter_projec...,RecSys-Content-Based-movies-py-v1.ipynb,18443,2021-02-18 22:37:24
14,/Users/sanamjankurban/Documents/Jupyter_projec...,RecSys-Collaborative-Filtering-movies-py-v1.ipynb,33260,2021-02-18 22:37:24
15,/Users/sanamjankurban/Documents/Jupyter_projec...,Clas-K-Nearest-neighbors-CustCat-py-v1.ipynb,21543,2021-02-18 22:37:24
16,/Users/sanamjankurban/Documents/Jupyter_projec...,Clas-Decision-Trees-drug-py-v1.ipynb,21086,2021-02-18 22:37:24
17,/Users/sanamjankurban/Documents/Jupyter_projec...,Clas-K-Nearest-neighbors-CustCat-py-v1-checkpo...,21543,2021-02-18 22:37:24
18,/Users/sanamjankurban/Documents/Jupyter_projec...,Reg-Polynomial-Regression-Co2-py-v1.ipynb,17624,2021-02-18 22:37:24
19,/Users/sanamjankurban/Documents/Jupyter_projec...,Reg-NoneLinearRegression-py-v1.ipynb,16549,2021-02-18 22:37:24
20,/Users/sanamjankurban/Documents/Jupyter_projec...,Reg-Mulitple-Linear-Regression-Co2-py-v1.ipynb,16123,2021-02-18 22:37:24
21,/Users/sanamjankurban/Documents/Jupyter_projec...,Reg-Simple-Linear-Regression-Co2-py-v1.ipynb,18310,2021-02-18 22:37:24
22,/Users/sanamjankurban/Documents/Jupyter_projec...,From-Modeling-to-Evaluation-v2.0.ipynb,34865,2021-02-18 22:37:23
23,/Users/sanamjankurban/Documents/Jupyter_projec...,From-Understanding-to-Preparation-v2.0.ipynb,30874,2021-02-18 22:37:23
24,/Users/sanamjankurban/Documents/Jupyter_projec...,From-Problem-to-Approach-v2.0.ipynb,25799,2021-02-18 22:37:23
25,/Users/sanamjankurban/Documents/Jupyter_projec...,From-Requirements-to-Collection-v2.0.ipynb,13299,2021-02-18 22:37:23
26,/Users/sanamjankurban/Documents/Jupyter_projec...,capstone-project.ipynb,31724,2021-02-18 22:37:22
27,/Users/sanamjankurban/Documents/Jupyter_projec...,Clustering-k-means-py-v1.0.ipynb,30157,2021-02-18 22:37:22
28,/Users/sanamjankurban/Documents/Jupyter_projec...,Neighborhoods-New-York-py-v1.0.ipynb,38311,2021-02-18 22:37:22
29,/Users/sanamjankurban/Documents/Jupyter_projec...,Segmenting and Clustering Neighborhoods in Tor...,25422,2021-02-18 22:37:22
...,...,...,...,...
36,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-5-2-Numpy2D.ipynb,17551,2021-02-18 22:37:24
37,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-4-1-ReadFile.ipynb,15195,2021-02-18 22:37:24
38,/Users/sanamjankurban/Documents/Jupyter_projec...,project.ipynb,62363,2021-02-18 22:37:24
39,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-2-2-Lists.ipynb,23056,2021-02-18 22:37:24
40,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-2-1-Tuples.ipynb,26144,2021-02-18 22:37:24
41,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-2-4-Sets.ipynb,18836,2021-02-18 22:37:24
42,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-2-3-Dictionaries.ipynb,17301,2021-02-18 22:37:24
43,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-1-2-Strings.ipynb,27271,2021-02-18 22:37:24
44,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-1-1-Types.ipynb,39525,2021-02-18 22:37:24
45,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-3-3-Functions.ipynb,31829,2021-02-18 22:37:24
46,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-3-4-Classes.ipynb,21977,2021-02-18 22:37:24
47,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-3-1-Conditions.ipynb,28636,2021-02-18 22:37:24
48,/Users/sanamjankurban/Documents/Jupyter_projec...,PY0101EN-3-2-Loops.ipynb,16167,2021-02-18 22:37:24
49,/Users/sanamjankurban/Documents/Jupyter_projec...,exploratory_data_analysis1.ipynb,44066,2021-02-18 22:37:22
50,/Users/sanamjankurban/Documents/Jupyter_projec...,model_evaluation_and_refinement.ipynb,41924,2021-02-18 22:37:23
51,/Users/sanamjankurban/Documents/Jupyter_projec...,datasets.ipynb,17328,2021-02-18 22:37:22
52,/Users/sanamjankurban/Documents/Jupyter_projec...,data_wrangling.ipynb,40351,2021-02-18 22:37:22
53,/Users/sanamjankurban/Documents/Jupyter_projec...,model_development.ipynb,47985,2021-02-18 22:37:23
54,/Users/sanamjankurban/Documents/Jupyter_projec...,final.ipynb,1981,2021-02-18 22:37:24
55,/Users/sanamjankurban/Documents/Jupyter_projec...,Working with a real world data-set using SQL a...,20284,2021-02-18 22:37:23
56,/Users/sanamjankurban/Documents/Jupyter_projec...,Notebook for Peer Assignment.ipynb,34244,2021-02-18 22:37:23
57,/Users/sanamjankurban/Documents/Jupyter_projec...,Access DB2 on Cloud using Python.ipynb,15293,2021-02-18 22:37:23
58,/Users/sanamjankurban/Documents/Jupyter_projec...,Analyzing a real world data-set with SQL and P...,12066,2021-02-18 22:37:23
59,/Users/sanamjankurban/Documents/Jupyter_projec...,Connect to Db2 database on Cloud using Python....,7946,2021-02-18 22:37:23
60,/Users/sanamjankurban/Documents/Jupyter_projec...,Accessing Databases with SQL Magic.ipynb,12155,2021-02-18 22:37:23
61,/Users/sanamjankurban/Documents/Jupyter_projec...,Waffle-Charts-Word-Clouds-and-Regression-Plots...,58732,2021-02-18 22:37:23
62,/Users/sanamjankurban/Documents/Jupyter_projec...,Generating-Maps-in-Python-py-v2.0.ipynb,45514,2021-02-18 22:37:23
63,/Users/sanamjankurban/Documents/Jupyter_projec...,Introduction-to-Matplotlib-and-Line-Plots-py-v...,49979,2021-02-18 22:37:23
64,/Users/sanamjankurban/Documents/Jupyter_projec...,Pie-Charts-Box-Plots-Scatter-Plots-and-Bubble-...,64413,2021-02-18 22:37:23
65,/Users/sanamjankurban/Documents/Jupyter_projec...,Area-Plots-Histograms-and-Bar-Charts-py-v2.0.i...,54266,2021-02-18 22:37:23

In [6]:
import os
str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"
for file in os.listdir(str):
    if os.path.isfile(os.path.join(str, file)):
        print(file)

.DS_Store

In [1]:
import glob, os

In [8]:
str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"
os.chdir(str)
for file in glob.glob("*.ipynb"):
    print(file)

In [9]:
for file in os.listdir(str):
    if file.endswith(".ipynb"):
        print(os.path.join(str, file))

In [10]:
for root, dirs, files in os.walk(str):
    for file in files:
        if file.endswith(".ipynb"):
            print(os.path.join(root, file))

/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/add_folder/Course 3 - Week 1 - Exercise-answer.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/01. Data Preprocessing/Data Preprocessing_G.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/01. Simple_Linear_Regression/Simple LinearRegression_G.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/02. Multiple_Linear_Regression/Multiple_Linear_Regression_G.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/04. Support Vector Regression/Support_Vector_Regression-(SVR)_G.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/05. Decision Tree Regression/Decision-Tree_Regression_G.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/02. Regression/03. Polynomial Regression/Polynomial_Linear_Regression_G.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/02. K-Nearest_Neighbors/K-Nearest-Neighbor_(KNN)_Classifier_G.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Machine-Learning-AtoZ/03. Classification/01. Logistic_Regression/Classification-Logistic_Regression_G.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week4- Clustering/Clus-DBSCN-weather-py-v1.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week4- Clustering/Clus-Hierarchical-Cars-py-v1.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week4- Clustering/Clus-K-Means-Customer-Seg-py-v1.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/final-project/final-solution.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/final-project/final project.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week5- Recommender Systems/RecSys-Content-Based-movies-py-v1.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week5- Recommender Systems/RecSys-Collaborative-Filtering-movies-py-v1.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification/Clas-K-Nearest-neighbors-CustCat-py-v1.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification/Clas-Decision-Trees-drug-py-v1.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week3- Classification/.ipynb_checkpoints/Clas-K-Nearest-neighbors-CustCat-py-v1-checkpoint.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression/Reg-Polynomial-Regression-Co2-py-v1.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression/Reg-NoneLinearRegression-py-v1.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression/Reg-Mulitple-Linear-Regression-Co2-py-v1.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Machine Learning with Python/week2- Regression/Reg-Simple-Linear-Regression-Co2-py-v1.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week2- From Understanding to Preparation and From Modelin to Evaluation/From-Modeling-to-Evaluation-v2.0.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week2- From Understanding to Preparation and From Modelin to Evaluation/From-Understanding-to-Preparation-v2.0.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week1- From Problem to Approach and From Requirements to Collection/From-Problem-to-Approach-v2.0.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Science Methodology/week1- From Problem to Approach and From Requirements to Collection/From-Requirements-to-Collection-v2.0.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/capstone-project/capstone-project.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/Clustering-k-means-py-v1.0.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/Neighborhoods-New-York-py-v1.0.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/project/Segmenting and Clustering Neighborhoods in Toronto.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/project/Segmenting and Clustering Neighborhoods with Coordinates.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module3/project/Segmenting and Clustering Neighborhoods Final.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module2/Foursquare-API-py-v1.0.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Applied Data Science Capstone Project/module1/assignment1.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python/PY0101EN-5-1-Numpy1D.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python/PY0101EN-4-2-WriteFile.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python/PY0101EN-5-2-Numpy2D.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week4- Working with Data in Python/PY0101EN-4-1-ReadFile.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week5- Fake Album Cover Game/project.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures/PY0101EN-2-2-Lists.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures/PY0101EN-2-1-Tuples.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures/PY0101EN-2-4-Sets.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week2- Python Data Structures/PY0101EN-2-3-Dictionaries.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week1- Python/PY0101EN-1-2-Strings.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week1- Python/PY0101EN-1-1-Types.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming/PY0101EN-3-3-Functions.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming/PY0101EN-3-4-Classes.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming/PY0101EN-3-1-Conditions.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Python for Data Science/week3- Python Programming/PY0101EN-3-2-Loops.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week3 - Exploratory Data Analysis/exploratory_data_analysis1.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week5 - Model Evaluation/model_evaluation_and_refinement.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week1 - Datasets/datasets.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week2 - Data Wrangling/data_wrangling.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Analysis with Python/week4 - Model Development/model_development.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Open Source tools for Data Science/project/final.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week4- Assignment/Working with a real world data-set using SQL and Python.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week4- Assignment/Notebook for Peer Assignment.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python/Access DB2 on Cloud using Python.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python/Analyzing a real world data-set with SQL and Python.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python/Connect to Db2 database on Cloud using Python.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Databases and SQL for Data Science/week3- Accessing Databases using Python/Accessing Databases with SQL Magic.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week3 - Advanced Visualizations and Geospatial Data/Waffle-Charts-Word-Clouds-and-Regression-Plots-py-v2.0.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week3 - Advanced Visualizations and Geospatial Data/Generating-Maps-in-Python-py-v2.0.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week1 - Data Visualization Tools/Introduction-to-Matplotlib-and-Line-Plots-py-v2.0.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week2 - Basic and Specialized Visualization Tools/Pie-Charts-Box-Plots-Scatter-Plots-and-Bubble-Plots-py-v2.0.ipynb
/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/Applied-Data-Science-Specialization-IBM/IBM - Data Visualization with Python/week2 - Basic and Specialized Visualization Tools/Area-Plots-Histograms-and-Bar-Charts-py-v2.0.ipynb

In [64]:
import numpy as np
import time
import datetime

In [65]:
str = "/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/"

In [66]:
def get_file_list():
    file_list = []
    delta = datetime.timedelta(days=30)
    now = datetime.datetime.now()
    
    for p, d, f in os.walk(str):
        for filename in f:
            
            if filename.endswith(".ipynb"):
                fullpath = os.path.join(p, filename)
                file_name = os.path.join(filename)
                size = os.path.getsize(fullpath)
                time_file = datetime.datetime.fromtimestamp(os.path.getctime(fullpath))
                if (now-delta < time_file):
                    create_time = time_file.strftime("%Y-%m-%d %H:%M:%S")
                    item_list = (fullpath, filename, size, create_time)
                    file_list.append(item_list)
    return file_list

In [67]:
last_result = get_file_list()
last_result

[('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/add_folder/Course 3 - Week 1 - Exercise-answer.ipynb',
  'Course 3 - Week 1 - Exercise-answer.ipynb',
  21141,
  '2021-06-18 17:53:19'),
 ('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/ML Courses/add_folder/read_folder.ipynb',
  'read_folder.ipynb',
  31696,
  '2021-06-21 16:18:03')]