In [9]:
import numpy as np
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt

In [10]:
from pathlib import Path
data_dir = Path('/Users/sanamjankurban/Documents/Jupyter_projects/Data Analysis Examples/DataBases')

import os
os.listdir(data_dir)

['-disbtribution-worldwide-2020-03-22.csv',
 'hypothyroid.csv',
 'dataset.xlsx',
 'Mall_Customers.csv',
 '-Investment-Tracker-2019-Fall-FINAL.csv',
 '.DS_Store',
 'nesarc_pds.csv',
 '-disbtribution-worldwide-2020-03-31.csv',
 'AssigmentsData',
 'TÜRKİYE son veriler.xlsx',
 'Rapor 7260 ABCF MO MT Mean Duration Session.xlsx',
 'Sample - Superstore.xls',
 'addhealth_pds.csv',
 'Classified Data',
 'College_Data',
 'winequality-red.csv',
 'FuelConsumptionCo2.csv',
 'adult_income_data.csv',
 'COVID-19-geographic-disbtribution-worldwide-2020-03-31.xlsx',
 'tree_addhealth.csv',
 'China-Global-Investment-Tracker-2019-Fall-FINAL.xlsx',
 'USA_Housing.csv',
 'Readme.md',
 'titanic_test.csv',
 'marscrater_pds.csv',
 'covid19-global-forecasting-week-1.zip',
 'slump_test.csv',
 'covid19-global-forecasting-week-1',
 'ool_pds.csv',
 'china_gdp.csv',
 'KNN_Project_Data',
 'Height_Weight.xlsx',
 'dataset.csv',
 'gapminder.csv',
 'loan_data.csv',
 'Concrete_Data.xls',
 'kyphosis.csv',
 'titanic_train.csv',
 'wine.data.csv']

In [13]:
df = pd.read_excel(data_dir/"Rapor 7260 ABCF MO MT Mean Duration Session.xlsx", "Q1")
df.head(10)

,DATETIME,NE,ABCF_MO_SES_DUR,ABCF_MO_SES_DUR_PRE,ABCF_MT_SES_DUR,ABCF_MT_SES_DUR_PRE
0,2/23/2021 2:00:00 PM,SE2900AHLH02,92.50,97.25,91.25,93.50
1,2/23/2021 2:00:00 PM,SE2900UMRH02,91.50,95.75,90.50,92.00
2,2/23/2021 2:00:00 PM,SE2980AHLH06,94.50,98.25,88.50,91.00
3,2/23/2021 2:00:00 PM,SE2980AHLH07,94.25,98.00,87.75,91.75
4,2/23/2021 2:00:00 PM,SE2980IZMH04,89.25,93.00,84.50,88.25
5,2/23/2021 2:00:00 PM,SE2980IZMH05,90.00,93.25,83.25,87.50
6,2/23/2021 2:00:00 PM,SE2980UMRH05,94.75,98.25,88.00,91.75
7,2/23/2021 2:00:00 PM,SE2980UMRH06,95.00,98.50,87.25,91.25
8,2/23/2021 1:00:00 PM,SE2900AHLH02,97.25,100.00,93.50,101.75
9,2/23/2021 1:00:00 PM,SE2900UMRH02,95.75,96.00,92.00,94.50

In [15]:
df["MO_VALUE"] = df.ABCF_MO_SES_DUR_PRE - df.ABCF_MO_SES_DUR
df["MT_VALUE"] = df.ABCF_MT_SES_DUR_PRE - df.ABCF_MT_SES_DUR
df

,DATETIME,NE,ABCF_MO_SES_DUR,ABCF_MO_SES_DUR_PRE,ABCF_MT_SES_DUR,ABCF_MT_SES_DUR_PRE,MO_VALUE,MT_VALUE
0,2/23/2021 2:00:00 PM,SE2900AHLH02,92.50,97.25,91.25,93.50,4.75,2.25
1,2/23/2021 2:00:00 PM,SE2900UMRH02,91.50,95.75,90.50,92.00,4.25,1.50
2,2/23/2021 2:00:00 PM,SE2980AHLH06,94.50,98.25,88.50,91.00,3.75,2.50
3,2/23/2021 2:00:00 PM,SE2980AHLH07,94.25,98.00,87.75,91.75,3.75,4.00
4,2/23/2021 2:00:00 PM,SE2980IZMH04,89.25,93.00,84.50,88.25,3.75,3.75
5,2/23/2021 2:00:00 PM,SE2980IZMH05,90.00,93.25,83.25,87.50,3.25,4.25
6,2/23/2021 2:00:00 PM,SE2980UMRH05,94.75,98.25,88.00,91.75,3.50,3.75
7,2/23/2021 2:00:00 PM,SE2980UMRH06,95.00,98.50,87.25,91.25,3.50,4.00
8,2/23/2021 1:00:00 PM,SE2900AHLH02,97.25,100.00,93.50,101.75,2.75,8.25
9,2/23/2021 1:00:00 PM,SE2900UMRH02,95.75,96.00,92.00,94.50,0.25,2.50
10,2/23/2021 1:00:00 PM,SE2980AHLH06,98.25,102.25,91.00,95.25,4.00,4.25
11,2/23/2021 1:00:00 PM,SE2980AHLH07,98.00,101.25,91.75,95.50,3.25,3.75
12,2/23/2021 1:00:00 PM,SE2980IZMH04,93.00,95.75,88.25,90.00,2.75,1.75
13,2/23/2021 1:00:00 PM,SE2980IZMH05,93.25,96.25,87.50,88.75,3.00,1.25
14,2/23/2021 1:00:00 PM,SE2980UMRH05,98.25,100.25,91.75,91.75,2.00,0.00
15,2/23/2021 1:00:00 PM,SE2980UMRH06,98.50,101.00,91.25,92.00,2.50,0.75
16,2/23/2021 12:00:00 PM,SE2900AHLH02,100.00,97.00,101.75,96.25,-3.00,-5.50
17,2/23/2021 12:00:00 PM,SE2900UMRH02,96.00,92.50,94.50,88.50,-3.50,-6.00
18,2/23/2021 12:00:00 PM,SE2980AHLH06,102.25,99.00,95.25,91.00,-3.25,-4.25
19,2/23/2021 12:00:00 PM,SE2980AHLH07,101.25,97.50,95.50,90.00,-3.75,-5.50
20,2/23/2021 12:00:00 PM,SE2980IZMH04,95.75,93.25,90.00,85.25,-2.50,-4.75
21,2/23/2021 12:00:00 PM,SE2980IZMH05,96.25,92.00,88.75,84.25,-4.25,-4.50
22,2/23/2021 12:00:00 PM,SE2980UMRH05,100.25,97.25,91.75,87.75,-3.00,-4.00
23,2/23/2021 12:00:00 PM,SE2980UMRH06,101.00,97.75,92.00,86.75,-3.25,-5.25
24,2/23/2021 11:00:00 AM,SE2900AHLH02,97.00,89.00,96.25,84.75,-8.00,-11.50
25,2/23/2021 11:00:00 AM,SE2900UMRH02,92.50,84.50,88.50,82.25,-8.00,-6.25
26,2/23/2021 11:00:00 AM,SE2980AHLH06,99.00,89.00,91.00,80.25,-10.00,-10.75
27,2/23/2021 11:00:00 AM,SE2980AHLH07,97.50,88.50,90.00,79.75,-9.00,-10.25
28,2/23/2021 11:00:00 AM,SE2980IZMH04,93.25,84.50,85.25,75.50,-8.75,-9.75
29,2/23/2021 11:00:00 AM,SE2980IZMH05,92.00,85.25,84.25,76.25,-6.75,-8.00
...,...,...,...,...,...,...,...,...
58,2/23/2021 7:00:00 AM,SE2980AHLH06,51.00,53.00,44.00,50.25,2.00,6.25
59,2/23/2021 7:00:00 AM,SE2980AHLH07,48.25,52.50,46.50,49.25,4.25,2.75
60,2/23/2021 7:00:00 AM,SE2980IZMH04,48.75,50.00,45.75,48.75,1.25,3.00
61,2/23/2021 7:00:00 AM,SE2980IZMH05,47.00,49.75,45.75,51.00,2.75,5.25
62,2/23/2021 7:00:00 AM,SE2980UMRH05,48.75,52.25,46.25,49.00,3.50,2.75
63,2/23/2021 7:00:00 AM,SE2980UMRH06,49.00,52.25,47.25,46.75,3.25,-0.50
64,2/23/2021 6:00:00 AM,SE2900AHLH02,50.25,71.75,47.50,51.25,21.50,3.75
65,2/23/2021 6:00:00 AM,SE2900UMRH02,53.75,65.00,58.25,85.00,11.25,26.75
66,2/23/2021 6:00:00 AM,SE2980AHLH06,53.00,89.25,50.25,74.25,36.25,24.00
67,2/23/2021 6:00:00 AM,SE2980AHLH07,52.50,101.50,49.25,97.25,49.00,48.00
68,2/23/2021 6:00:00 AM,SE2980IZMH04,50.00,79.00,48.75,78.25,29.00,29.50
69,2/23/2021 6:00:00 AM,SE2980IZMH05,49.75,96.75,51.00,71.25,47.00,20.25
70,2/23/2021 6:00:00 AM,SE2980UMRH05,52.25,86.75,49.00,86.50,34.50,37.50
71,2/23/2021 6:00:00 AM,SE2980UMRH06,52.25,90.75,46.75,82.75,38.50,36.00
72,2/23/2021 5:00:00 AM,SE2900AHLH02,71.75,128.25,51.25,133.50,56.50,82.25
73,2/23/2021 5:00:00 AM,SE2900UMRH02,65.00,112.25,85.00,132.75,47.25,47.75
74,2/23/2021 5:00:00 AM,SE2980AHLH06,89.25,174.25,74.25,180.25,85.00,106.00
75,2/23/2021 5:00:00 AM,SE2980AHLH07,101.50,173.75,97.25,173.50,72.25,76.25
76,2/23/2021 5:00:00 AM,SE2980IZMH04,79.00,127.50,78.25,157.50,48.50,79.25
77,2/23/2021 5:00:00 AM,SE2980IZMH05,96.75,171.50,71.25,136.00,74.75,64.75
78,2/23/2021 5:00:00 AM,SE2980UMRH05,86.75,161.50,86.50,154.50,74.75,68.00
79,2/23/2021 5:00:00 AM,SE2980UMRH06,90.75,155.50,82.75,143.00,64.75,60.25
80,2/23/2021 4:00:00 AM,SE2900AHLH02,128.25,285.25,133.50,299.75,157.00,166.25
81,2/23/2021 4:00:00 AM,SE2900UMRH02,112.25,267.75,132.75,144.25,155.50,11.50
82,2/23/2021 4:00:00 AM,SE2980AHLH06,174.25,230.25,180.25,242.50,56.00,62.25
83,2/23/2021 4:00:00 AM,SE2980AHLH07,173.75,279.00,173.50,265.25,105.25,91.75
84,2/23/2021 4:00:00 AM,SE2980IZMH04,127.50,223.50,157.50,197.25,96.00,39.75
85,2/23/2021 4:00:00 AM,SE2980IZMH05,171.50,258.25,136.00,228.75,86.75,92.75
86,2/23/2021 4:00:00 AM,SE2980UMRH05,161.50,225.00,154.50,262.75,63.50,108.25
87,2/23/2021 4:00:00 AM,SE2980UMRH06,155.50,245.00,143.00,276.25,89.50,133.25